package com.avnet.alapps.model.gsfcreport;

// Generated Aug 31, 2015 4:15:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private BigDecimal customerId;
	private Date createDt;
	private BigDecimal createUserId;
	private String customerNm;
	private BigDecimal customerNo;
	private BigDecimal defaultPostalAddressId;
	private BigDecimal industryClassId;
	private BigDecimal preferredLanguageId;
	private BigDecimal languageId;
	private Date updateDt;
	private BigDecimal updateUserId;
	private BigDecimal minimumOrderCostAm;
	private Set firstArticles = new HashSet(0);
	private Set workOrders = new HashSet(0);

	public Customer() {
	}

	public Customer(BigDecimal customerId, Date createDt,
			BigDecimal createUserId, String customerNm, BigDecimal customerNo,
			BigDecimal languageId, Date updateDt, BigDecimal updateUserId) {
		this.customerId = customerId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.customerNm = customerNm;
		this.customerNo = customerNo;
		this.languageId = languageId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public Customer(BigDecimal customerId, Date createDt,
			BigDecimal createUserId, String customerNm, BigDecimal customerNo,
			BigDecimal defaultPostalAddressId, BigDecimal industryClassId,
			BigDecimal preferredLanguageId, BigDecimal languageId,
			Date updateDt, BigDecimal updateUserId,
			BigDecimal minimumOrderCostAm, Set firstArticles, Set workOrders) {
		this.customerId = customerId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.customerNm = customerNm;
		this.customerNo = customerNo;
		this.defaultPostalAddressId = defaultPostalAddressId;
		this.industryClassId = industryClassId;
		this.preferredLanguageId = preferredLanguageId;
		this.languageId = languageId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.minimumOrderCostAm = minimumOrderCostAm;
		this.firstArticles = firstArticles;
		this.workOrders = workOrders;
	}

	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getCustomerNm() {
		return this.customerNm;
	}

	public void setCustomerNm(String customerNm) {
		this.customerNm = customerNm;
	}

	public BigDecimal getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(BigDecimal customerNo) {
		this.customerNo = customerNo;
	}

	public BigDecimal getDefaultPostalAddressId() {
		return this.defaultPostalAddressId;
	}

	public void setDefaultPostalAddressId(BigDecimal defaultPostalAddressId) {
		this.defaultPostalAddressId = defaultPostalAddressId;
	}

	public BigDecimal getIndustryClassId() {
		return this.industryClassId;
	}

	public void setIndustryClassId(BigDecimal industryClassId) {
		this.industryClassId = industryClassId;
	}

	public BigDecimal getPreferredLanguageId() {
		return this.preferredLanguageId;
	}

	public void setPreferredLanguageId(BigDecimal preferredLanguageId) {
		this.preferredLanguageId = preferredLanguageId;
	}

	public BigDecimal getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(BigDecimal languageId) {
		this.languageId = languageId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public BigDecimal getMinimumOrderCostAm() {
		return this.minimumOrderCostAm;
	}

	public void setMinimumOrderCostAm(BigDecimal minimumOrderCostAm) {
		this.minimumOrderCostAm = minimumOrderCostAm;
	}

	public Set getFirstArticles() {
		return this.firstArticles;
	}

	public void setFirstArticles(Set firstArticles) {
		this.firstArticles = firstArticles;
	}

	public Set getWorkOrders() {
		return this.workOrders;
	}

	public void setWorkOrders(Set workOrders) {
		this.workOrders = workOrders;
	}

}
