package com.avnet.alapps.model.gsfcreport;

// Generated Aug 31, 2015 4:15:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FirstArticle generated by hbm2java
 */
public class FirstArticle implements java.io.Serializable {

	private BigDecimal firstArticleId;
	private Site site;
	private Customer customer;
	private Date createDt;
	private BigDecimal createUserId;
	private String custFirstArticlePgmNm;
	private String custFirstArticlePgmRevNo;
	private String customerPartNo;
	private BigDecimal firstArticleRequestId;
	private BigDecimal firstArticleSerialNo;
	private Date firstArticleStatusDt;
	private BigDecimal firstArticleStatusId;
	private BigDecimal firstArticleStatusUserId;
	private Date updateDt;
	private BigDecimal updateUserId;
	private String customerApproverNm;
	private Date customerApprovalDt;
	private String avnetLogisticsGeneratedFl;
	private String avnetLogisticsLegacyFl;
	private String specificationFileNm;
	private String endCustomerPartNo;
	private BigDecimal contractManufacturerSiteId;
	private BigDecimal estimatedAnnualPartQt;
	private String customerDrawingRevisionNo;
	private String customerPartRevisionNo;
	private String itarFl;
	private String businessUnitTx;
	private String platformTx;

	public FirstArticle() {
	}

	public FirstArticle(BigDecimal firstArticleId, Date createDt,
			BigDecimal createUserId, BigDecimal firstArticleSerialNo,
			Date firstArticleStatusDt, BigDecimal firstArticleStatusId,
			BigDecimal firstArticleStatusUserId, Date updateDt,
			BigDecimal updateUserId, String avnetLogisticsGeneratedFl,
			String avnetLogisticsLegacyFl, String itarFl) {
		this.firstArticleId = firstArticleId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.firstArticleSerialNo = firstArticleSerialNo;
		this.firstArticleStatusDt = firstArticleStatusDt;
		this.firstArticleStatusId = firstArticleStatusId;
		this.firstArticleStatusUserId = firstArticleStatusUserId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.avnetLogisticsGeneratedFl = avnetLogisticsGeneratedFl;
		this.avnetLogisticsLegacyFl = avnetLogisticsLegacyFl;
		this.itarFl = itarFl;
	}

	public FirstArticle(BigDecimal firstArticleId, Site site,
			Customer customer, Date createDt, BigDecimal createUserId,
			String custFirstArticlePgmNm, String custFirstArticlePgmRevNo,
			String customerPartNo, BigDecimal firstArticleRequestId,
			BigDecimal firstArticleSerialNo, Date firstArticleStatusDt,
			BigDecimal firstArticleStatusId,
			BigDecimal firstArticleStatusUserId, Date updateDt,
			BigDecimal updateUserId, String customerApproverNm,
			Date customerApprovalDt, String avnetLogisticsGeneratedFl,
			String avnetLogisticsLegacyFl, String specificationFileNm,
			String endCustomerPartNo, BigDecimal contractManufacturerSiteId,
			BigDecimal estimatedAnnualPartQt, String customerDrawingRevisionNo,
			String customerPartRevisionNo, String itarFl,
			String businessUnitTx, String platformTx) {
		this.firstArticleId = firstArticleId;
		this.site = site;
		this.customer = customer;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.custFirstArticlePgmNm = custFirstArticlePgmNm;
		this.custFirstArticlePgmRevNo = custFirstArticlePgmRevNo;
		this.customerPartNo = customerPartNo;
		this.firstArticleRequestId = firstArticleRequestId;
		this.firstArticleSerialNo = firstArticleSerialNo;
		this.firstArticleStatusDt = firstArticleStatusDt;
		this.firstArticleStatusId = firstArticleStatusId;
		this.firstArticleStatusUserId = firstArticleStatusUserId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.customerApproverNm = customerApproverNm;
		this.customerApprovalDt = customerApprovalDt;
		this.avnetLogisticsGeneratedFl = avnetLogisticsGeneratedFl;
		this.avnetLogisticsLegacyFl = avnetLogisticsLegacyFl;
		this.specificationFileNm = specificationFileNm;
		this.endCustomerPartNo = endCustomerPartNo;
		this.contractManufacturerSiteId = contractManufacturerSiteId;
		this.estimatedAnnualPartQt = estimatedAnnualPartQt;
		this.customerDrawingRevisionNo = customerDrawingRevisionNo;
		this.customerPartRevisionNo = customerPartRevisionNo;
		this.itarFl = itarFl;
		this.businessUnitTx = businessUnitTx;
		this.platformTx = platformTx;
	}

	public BigDecimal getFirstArticleId() {
		return this.firstArticleId;
	}

	public void setFirstArticleId(BigDecimal firstArticleId) {
		this.firstArticleId = firstArticleId;
	}

	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getCustFirstArticlePgmNm() {
		return this.custFirstArticlePgmNm;
	}

	public void setCustFirstArticlePgmNm(String custFirstArticlePgmNm) {
		this.custFirstArticlePgmNm = custFirstArticlePgmNm;
	}

	public String getCustFirstArticlePgmRevNo() {
		return this.custFirstArticlePgmRevNo;
	}

	public void setCustFirstArticlePgmRevNo(String custFirstArticlePgmRevNo) {
		this.custFirstArticlePgmRevNo = custFirstArticlePgmRevNo;
	}

	public String getCustomerPartNo() {
		return this.customerPartNo;
	}

	public void setCustomerPartNo(String customerPartNo) {
		this.customerPartNo = customerPartNo;
	}

	public BigDecimal getFirstArticleRequestId() {
		return this.firstArticleRequestId;
	}

	public void setFirstArticleRequestId(BigDecimal firstArticleRequestId) {
		this.firstArticleRequestId = firstArticleRequestId;
	}

	public BigDecimal getFirstArticleSerialNo() {
		return this.firstArticleSerialNo;
	}

	public void setFirstArticleSerialNo(BigDecimal firstArticleSerialNo) {
		this.firstArticleSerialNo = firstArticleSerialNo;
	}

	public Date getFirstArticleStatusDt() {
		return this.firstArticleStatusDt;
	}

	public void setFirstArticleStatusDt(Date firstArticleStatusDt) {
		this.firstArticleStatusDt = firstArticleStatusDt;
	}

	public BigDecimal getFirstArticleStatusId() {
		return this.firstArticleStatusId;
	}

	public void setFirstArticleStatusId(BigDecimal firstArticleStatusId) {
		this.firstArticleStatusId = firstArticleStatusId;
	}

	public BigDecimal getFirstArticleStatusUserId() {
		return this.firstArticleStatusUserId;
	}

	public void setFirstArticleStatusUserId(BigDecimal firstArticleStatusUserId) {
		this.firstArticleStatusUserId = firstArticleStatusUserId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public String getCustomerApproverNm() {
		return this.customerApproverNm;
	}

	public void setCustomerApproverNm(String customerApproverNm) {
		this.customerApproverNm = customerApproverNm;
	}

	public Date getCustomerApprovalDt() {
		return this.customerApprovalDt;
	}

	public void setCustomerApprovalDt(Date customerApprovalDt) {
		this.customerApprovalDt = customerApprovalDt;
	}

	public String getAvnetLogisticsGeneratedFl() {
		return this.avnetLogisticsGeneratedFl;
	}

	public void setAvnetLogisticsGeneratedFl(String avnetLogisticsGeneratedFl) {
		this.avnetLogisticsGeneratedFl = avnetLogisticsGeneratedFl;
	}

	public String getAvnetLogisticsLegacyFl() {
		return this.avnetLogisticsLegacyFl;
	}

	public void setAvnetLogisticsLegacyFl(String avnetLogisticsLegacyFl) {
		this.avnetLogisticsLegacyFl = avnetLogisticsLegacyFl;
	}

	public String getSpecificationFileNm() {
		return this.specificationFileNm;
	}

	public void setSpecificationFileNm(String specificationFileNm) {
		this.specificationFileNm = specificationFileNm;
	}

	public String getEndCustomerPartNo() {
		return this.endCustomerPartNo;
	}

	public void setEndCustomerPartNo(String endCustomerPartNo) {
		this.endCustomerPartNo = endCustomerPartNo;
	}

	public BigDecimal getContractManufacturerSiteId() {
		return this.contractManufacturerSiteId;
	}

	public void setContractManufacturerSiteId(
			BigDecimal contractManufacturerSiteId) {
		this.contractManufacturerSiteId = contractManufacturerSiteId;
	}

	public BigDecimal getEstimatedAnnualPartQt() {
		return this.estimatedAnnualPartQt;
	}

	public void setEstimatedAnnualPartQt(BigDecimal estimatedAnnualPartQt) {
		this.estimatedAnnualPartQt = estimatedAnnualPartQt;
	}

	public String getCustomerDrawingRevisionNo() {
		return this.customerDrawingRevisionNo;
	}

	public void setCustomerDrawingRevisionNo(String customerDrawingRevisionNo) {
		this.customerDrawingRevisionNo = customerDrawingRevisionNo;
	}

	public String getCustomerPartRevisionNo() {
		return this.customerPartRevisionNo;
	}

	public void setCustomerPartRevisionNo(String customerPartRevisionNo) {
		this.customerPartRevisionNo = customerPartRevisionNo;
	}

	public String getItarFl() {
		return this.itarFl;
	}

	public void setItarFl(String itarFl) {
		this.itarFl = itarFl;
	}

	public String getBusinessUnitTx() {
		return this.businessUnitTx;
	}

	public void setBusinessUnitTx(String businessUnitTx) {
		this.businessUnitTx = businessUnitTx;
	}

	public String getPlatformTx() {
		return this.platformTx;
	}

	public void setPlatformTx(String platformTx) {
		this.platformTx = platformTx;
	}

}
