package com.avnet.alapps.model.gsfcreport;

// Generated Aug 31, 2015 4:15:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Site generated by hbm2java
 */
public class Site implements java.io.Serializable {

	private BigDecimal siteId;
	private Date createDt;
	private BigDecimal createUserId;
	private String siteCd;
	private String siteNm;
	private Date updateDt;
	private BigDecimal updateUserId;
	private Date cutoffTm;
	private BigDecimal timeZoneId;
	private BigDecimal primaryPostalAddressId;
	private String activeFl;
	private String commentTx;
	private BigDecimal serviceCostMethodFactorNo;
	private BigDecimal defaultSourceId;
	private String siteDs;
	private String sourcePlantId;
	private Set firstArticles = new HashSet(0);
	private Set workOrders = new HashSet(0);

	public Site() {
	}

	public Site(BigDecimal siteId, Date createDt, BigDecimal createUserId,
			String siteCd, String siteNm, Date updateDt,
			BigDecimal updateUserId, Date cutoffTm, BigDecimal timeZoneId,
			BigDecimal primaryPostalAddressId, String activeFl,
			BigDecimal serviceCostMethodFactorNo, BigDecimal defaultSourceId) {
		this.siteId = siteId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.siteCd = siteCd;
		this.siteNm = siteNm;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.cutoffTm = cutoffTm;
		this.timeZoneId = timeZoneId;
		this.primaryPostalAddressId = primaryPostalAddressId;
		this.activeFl = activeFl;
		this.serviceCostMethodFactorNo = serviceCostMethodFactorNo;
		this.defaultSourceId = defaultSourceId;
	}

	public Site(BigDecimal siteId, Date createDt, BigDecimal createUserId,
			String siteCd, String siteNm, Date updateDt,
			BigDecimal updateUserId, Date cutoffTm, BigDecimal timeZoneId,
			BigDecimal primaryPostalAddressId, String activeFl,
			String commentTx, BigDecimal serviceCostMethodFactorNo,
			BigDecimal defaultSourceId, String siteDs, String sourcePlantId,
			Set firstArticles, Set workOrders) {
		this.siteId = siteId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.siteCd = siteCd;
		this.siteNm = siteNm;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.cutoffTm = cutoffTm;
		this.timeZoneId = timeZoneId;
		this.primaryPostalAddressId = primaryPostalAddressId;
		this.activeFl = activeFl;
		this.commentTx = commentTx;
		this.serviceCostMethodFactorNo = serviceCostMethodFactorNo;
		this.defaultSourceId = defaultSourceId;
		this.siteDs = siteDs;
		this.sourcePlantId = sourcePlantId;
		this.firstArticles = firstArticles;
		this.workOrders = workOrders;
	}

	public BigDecimal getSiteId() {
		return this.siteId;
	}

	public void setSiteId(BigDecimal siteId) {
		this.siteId = siteId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getSiteCd() {
		return this.siteCd;
	}

	public void setSiteCd(String siteCd) {
		this.siteCd = siteCd;
	}

	public String getSiteNm() {
		return this.siteNm;
	}

	public void setSiteNm(String siteNm) {
		this.siteNm = siteNm;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getCutoffTm() {
		return this.cutoffTm;
	}

	public void setCutoffTm(Date cutoffTm) {
		this.cutoffTm = cutoffTm;
	}

	public BigDecimal getTimeZoneId() {
		return this.timeZoneId;
	}

	public void setTimeZoneId(BigDecimal timeZoneId) {
		this.timeZoneId = timeZoneId;
	}

	public BigDecimal getPrimaryPostalAddressId() {
		return this.primaryPostalAddressId;
	}

	public void setPrimaryPostalAddressId(BigDecimal primaryPostalAddressId) {
		this.primaryPostalAddressId = primaryPostalAddressId;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public String getCommentTx() {
		return this.commentTx;
	}

	public void setCommentTx(String commentTx) {
		this.commentTx = commentTx;
	}

	public BigDecimal getServiceCostMethodFactorNo() {
		return this.serviceCostMethodFactorNo;
	}

	public void setServiceCostMethodFactorNo(
			BigDecimal serviceCostMethodFactorNo) {
		this.serviceCostMethodFactorNo = serviceCostMethodFactorNo;
	}

	public BigDecimal getDefaultSourceId() {
		return this.defaultSourceId;
	}

	public void setDefaultSourceId(BigDecimal defaultSourceId) {
		this.defaultSourceId = defaultSourceId;
	}

	public String getSiteDs() {
		return this.siteDs;
	}

	public void setSiteDs(String siteDs) {
		this.siteDs = siteDs;
	}

	public String getSourcePlantId() {
		return this.sourcePlantId;
	}

	public void setSourcePlantId(String sourcePlantId) {
		this.sourcePlantId = sourcePlantId;
	}

	public Set getFirstArticles() {
		return this.firstArticles;
	}

	public void setFirstArticles(Set firstArticles) {
		this.firstArticles = firstArticles;
	}

	public Set getWorkOrders() {
		return this.workOrders;
	}

	public void setWorkOrders(Set workOrders) {
		this.workOrders = workOrders;
	}

}
