package com.avnet.alapps.model.gsfcreport;

// Generated Aug 31, 2015 4:15:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SourceWorkOrder generated by hbm2java
 */
public class SourceWorkOrder implements java.io.Serializable {

	private BigDecimal sourceWorkOrderId;
	private String billToCustomerNm;
	private String billToCustomerNo;
	private Date createDt;
	private BigDecimal createUserId;
	private String coiRejectReplaceMethodCd;
	private String customerPartNo;
	private String inventoryMfgCd;
	private String inventoryPartNo;
	private String invoiceLineNo;
	private String invoiceNo;
	private String manufacturerCd;
	private String manufacturerPartNo;
	private BigDecimal orderQt;
	private Date orderReleaseDt;
	private Date promisedDeliveryDt;
	private Date requiredDeliveryDt;
	private BigDecimal resaleUnitPriceAm;
	private String salesOrderLineNo;
	private String salesOrderNo;
	private Date shipByDt;
	private String shipToCustomerNm;
	private String shipToCustomerNo;
	private BigDecimal sourceId;
	private String specialHandlingCd;
	private Date updateDt;
	private BigDecimal updateUserId;
	private String salesPersonNm;
	private String sourceStorageLocationCd;
	private String sourceBatchId;
	private Set workOrders = new HashSet(0);

	public SourceWorkOrder() {
	}

	public SourceWorkOrder(BigDecimal sourceWorkOrderId, Date createDt,
			BigDecimal createUserId, String inventoryPartNo,
			BigDecimal orderQt, BigDecimal sourceId, Date updateDt,
			BigDecimal updateUserId) {
		this.sourceWorkOrderId = sourceWorkOrderId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.inventoryPartNo = inventoryPartNo;
		this.orderQt = orderQt;
		this.sourceId = sourceId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public SourceWorkOrder(BigDecimal sourceWorkOrderId,
			String billToCustomerNm, String billToCustomerNo, Date createDt,
			BigDecimal createUserId, String coiRejectReplaceMethodCd,
			String customerPartNo, String inventoryMfgCd,
			String inventoryPartNo, String invoiceLineNo, String invoiceNo,
			String manufacturerCd, String manufacturerPartNo,
			BigDecimal orderQt, Date orderReleaseDt, Date promisedDeliveryDt,
			Date requiredDeliveryDt, BigDecimal resaleUnitPriceAm,
			String salesOrderLineNo, String salesOrderNo, Date shipByDt,
			String shipToCustomerNm, String shipToCustomerNo,
			BigDecimal sourceId, String specialHandlingCd, Date updateDt,
			BigDecimal updateUserId, String salesPersonNm,
			String sourceStorageLocationCd, String sourceBatchId, Set workOrders) {
		this.sourceWorkOrderId = sourceWorkOrderId;
		this.billToCustomerNm = billToCustomerNm;
		this.billToCustomerNo = billToCustomerNo;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.coiRejectReplaceMethodCd = coiRejectReplaceMethodCd;
		this.customerPartNo = customerPartNo;
		this.inventoryMfgCd = inventoryMfgCd;
		this.inventoryPartNo = inventoryPartNo;
		this.invoiceLineNo = invoiceLineNo;
		this.invoiceNo = invoiceNo;
		this.manufacturerCd = manufacturerCd;
		this.manufacturerPartNo = manufacturerPartNo;
		this.orderQt = orderQt;
		this.orderReleaseDt = orderReleaseDt;
		this.promisedDeliveryDt = promisedDeliveryDt;
		this.requiredDeliveryDt = requiredDeliveryDt;
		this.resaleUnitPriceAm = resaleUnitPriceAm;
		this.salesOrderLineNo = salesOrderLineNo;
		this.salesOrderNo = salesOrderNo;
		this.shipByDt = shipByDt;
		this.shipToCustomerNm = shipToCustomerNm;
		this.shipToCustomerNo = shipToCustomerNo;
		this.sourceId = sourceId;
		this.specialHandlingCd = specialHandlingCd;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.salesPersonNm = salesPersonNm;
		this.sourceStorageLocationCd = sourceStorageLocationCd;
		this.sourceBatchId = sourceBatchId;
		this.workOrders = workOrders;
	}

	public BigDecimal getSourceWorkOrderId() {
		return this.sourceWorkOrderId;
	}

	public void setSourceWorkOrderId(BigDecimal sourceWorkOrderId) {
		this.sourceWorkOrderId = sourceWorkOrderId;
	}

	public String getBillToCustomerNm() {
		return this.billToCustomerNm;
	}

	public void setBillToCustomerNm(String billToCustomerNm) {
		this.billToCustomerNm = billToCustomerNm;
	}

	public String getBillToCustomerNo() {
		return this.billToCustomerNo;
	}

	public void setBillToCustomerNo(String billToCustomerNo) {
		this.billToCustomerNo = billToCustomerNo;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getCoiRejectReplaceMethodCd() {
		return this.coiRejectReplaceMethodCd;
	}

	public void setCoiRejectReplaceMethodCd(String coiRejectReplaceMethodCd) {
		this.coiRejectReplaceMethodCd = coiRejectReplaceMethodCd;
	}

	public String getCustomerPartNo() {
		return this.customerPartNo;
	}

	public void setCustomerPartNo(String customerPartNo) {
		this.customerPartNo = customerPartNo;
	}

	public String getInventoryMfgCd() {
		return this.inventoryMfgCd;
	}

	public void setInventoryMfgCd(String inventoryMfgCd) {
		this.inventoryMfgCd = inventoryMfgCd;
	}

	public String getInventoryPartNo() {
		return this.inventoryPartNo;
	}

	public void setInventoryPartNo(String inventoryPartNo) {
		this.inventoryPartNo = inventoryPartNo;
	}

	public String getInvoiceLineNo() {
		return this.invoiceLineNo;
	}

	public void setInvoiceLineNo(String invoiceLineNo) {
		this.invoiceLineNo = invoiceLineNo;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public String getManufacturerCd() {
		return this.manufacturerCd;
	}

	public void setManufacturerCd(String manufacturerCd) {
		this.manufacturerCd = manufacturerCd;
	}

	public String getManufacturerPartNo() {
		return this.manufacturerPartNo;
	}

	public void setManufacturerPartNo(String manufacturerPartNo) {
		this.manufacturerPartNo = manufacturerPartNo;
	}

	public BigDecimal getOrderQt() {
		return this.orderQt;
	}

	public void setOrderQt(BigDecimal orderQt) {
		this.orderQt = orderQt;
	}

	public Date getOrderReleaseDt() {
		return this.orderReleaseDt;
	}

	public void setOrderReleaseDt(Date orderReleaseDt) {
		this.orderReleaseDt = orderReleaseDt;
	}

	public Date getPromisedDeliveryDt() {
		return this.promisedDeliveryDt;
	}

	public void setPromisedDeliveryDt(Date promisedDeliveryDt) {
		this.promisedDeliveryDt = promisedDeliveryDt;
	}

	public Date getRequiredDeliveryDt() {
		return this.requiredDeliveryDt;
	}

	public void setRequiredDeliveryDt(Date requiredDeliveryDt) {
		this.requiredDeliveryDt = requiredDeliveryDt;
	}

	public BigDecimal getResaleUnitPriceAm() {
		return this.resaleUnitPriceAm;
	}

	public void setResaleUnitPriceAm(BigDecimal resaleUnitPriceAm) {
		this.resaleUnitPriceAm = resaleUnitPriceAm;
	}

	public String getSalesOrderLineNo() {
		return this.salesOrderLineNo;
	}

	public void setSalesOrderLineNo(String salesOrderLineNo) {
		this.salesOrderLineNo = salesOrderLineNo;
	}

	public String getSalesOrderNo() {
		return this.salesOrderNo;
	}

	public void setSalesOrderNo(String salesOrderNo) {
		this.salesOrderNo = salesOrderNo;
	}

	public Date getShipByDt() {
		return this.shipByDt;
	}

	public void setShipByDt(Date shipByDt) {
		this.shipByDt = shipByDt;
	}

	public String getShipToCustomerNm() {
		return this.shipToCustomerNm;
	}

	public void setShipToCustomerNm(String shipToCustomerNm) {
		this.shipToCustomerNm = shipToCustomerNm;
	}

	public String getShipToCustomerNo() {
		return this.shipToCustomerNo;
	}

	public void setShipToCustomerNo(String shipToCustomerNo) {
		this.shipToCustomerNo = shipToCustomerNo;
	}

	public BigDecimal getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(BigDecimal sourceId) {
		this.sourceId = sourceId;
	}

	public String getSpecialHandlingCd() {
		return this.specialHandlingCd;
	}

	public void setSpecialHandlingCd(String specialHandlingCd) {
		this.specialHandlingCd = specialHandlingCd;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public String getSalesPersonNm() {
		return this.salesPersonNm;
	}

	public void setSalesPersonNm(String salesPersonNm) {
		this.salesPersonNm = salesPersonNm;
	}

	public String getSourceStorageLocationCd() {
		return this.sourceStorageLocationCd;
	}

	public void setSourceStorageLocationCd(String sourceStorageLocationCd) {
		this.sourceStorageLocationCd = sourceStorageLocationCd;
	}

	public String getSourceBatchId() {
		return this.sourceBatchId;
	}

	public void setSourceBatchId(String sourceBatchId) {
		this.sourceBatchId = sourceBatchId;
	}

	public Set getWorkOrders() {
		return this.workOrders;
	}

	public void setWorkOrders(Set workOrders) {
		this.workOrders = workOrders;
	}

}
