package com.avnet.alapps.model.gsfcreport;

// Generated Aug 31, 2015 4:15:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkOrder generated by hbm2java
 */
public class WorkOrder implements java.io.Serializable {

	private BigDecimal workOrderId;
	private SourceWorkOrder sourceWorkOrder;
	private Site site;
	private Customer customer;
	private Date createDt;
	private BigDecimal createUserId;
	private String customerOwnedInventoryFl;
	private BigDecimal firstArticleSerialNo;
	private BigDecimal orderQt;
	private String shipDateCommitToSalesFl;
	private BigDecimal sourcePartId;
	private Date updateDt;
	private BigDecimal updateUserId;
	private BigDecimal workOrderNo;
	private BigDecimal workOrderStatusId;
	private String externalProblemFl;
	private BigDecimal valueAddUnitCostAm;
	private String commentTx;
	private String carrierServiceLevelCd;
	private String customerPurchaseOrderNo;
	private String miscellaneousTx01;
	private String partValueAddCd;
	private BigDecimal shippedQt;
	private String specialInstructionTx;
	private String onTimeDeliveryFl;
	private String kitPartNo;
	private String cutbackRequiredFl;
	private String orderLineNo;
	private String vendorNo;
	private String shopTicketFl;
	private String salesOrgNm;
	private String militaryOrderFl;
	private Set workOrderStatusHsts = new HashSet(0);

	public WorkOrder() {
	}

	public WorkOrder(BigDecimal workOrderId, SourceWorkOrder sourceWorkOrder,
			Site site, Date createDt, BigDecimal createUserId,
			BigDecimal orderQt, BigDecimal sourcePartId, Date updateDt,
			BigDecimal updateUserId, BigDecimal workOrderNo,
			BigDecimal workOrderStatusId, String externalProblemFl,
			String onTimeDeliveryFl, String shopTicketFl, String militaryOrderFl) {
		this.workOrderId = workOrderId;
		this.sourceWorkOrder = sourceWorkOrder;
		this.site = site;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.orderQt = orderQt;
		this.sourcePartId = sourcePartId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.workOrderNo = workOrderNo;
		this.workOrderStatusId = workOrderStatusId;
		this.externalProblemFl = externalProblemFl;
		this.onTimeDeliveryFl = onTimeDeliveryFl;
		this.shopTicketFl = shopTicketFl;
		this.militaryOrderFl = militaryOrderFl;
	}

	public WorkOrder(BigDecimal workOrderId, SourceWorkOrder sourceWorkOrder,
			Site site, Customer customer, Date createDt,
			BigDecimal createUserId, String customerOwnedInventoryFl,
			BigDecimal firstArticleSerialNo, BigDecimal orderQt,
			String shipDateCommitToSalesFl, BigDecimal sourcePartId,
			Date updateDt, BigDecimal updateUserId, BigDecimal workOrderNo,
			BigDecimal workOrderStatusId, String externalProblemFl,
			BigDecimal valueAddUnitCostAm, String commentTx,
			String carrierServiceLevelCd, String customerPurchaseOrderNo,
			String miscellaneousTx01, String partValueAddCd,
			BigDecimal shippedQt, String specialInstructionTx,
			String onTimeDeliveryFl, String kitPartNo,
			String cutbackRequiredFl, String orderLineNo, String vendorNo,
			String shopTicketFl, String salesOrgNm, String militaryOrderFl,
			Set workOrderStatusHsts) {
		this.workOrderId = workOrderId;
		this.sourceWorkOrder = sourceWorkOrder;
		this.site = site;
		this.customer = customer;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.customerOwnedInventoryFl = customerOwnedInventoryFl;
		this.firstArticleSerialNo = firstArticleSerialNo;
		this.orderQt = orderQt;
		this.shipDateCommitToSalesFl = shipDateCommitToSalesFl;
		this.sourcePartId = sourcePartId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.workOrderNo = workOrderNo;
		this.workOrderStatusId = workOrderStatusId;
		this.externalProblemFl = externalProblemFl;
		this.valueAddUnitCostAm = valueAddUnitCostAm;
		this.commentTx = commentTx;
		this.carrierServiceLevelCd = carrierServiceLevelCd;
		this.customerPurchaseOrderNo = customerPurchaseOrderNo;
		this.miscellaneousTx01 = miscellaneousTx01;
		this.partValueAddCd = partValueAddCd;
		this.shippedQt = shippedQt;
		this.specialInstructionTx = specialInstructionTx;
		this.onTimeDeliveryFl = onTimeDeliveryFl;
		this.kitPartNo = kitPartNo;
		this.cutbackRequiredFl = cutbackRequiredFl;
		this.orderLineNo = orderLineNo;
		this.vendorNo = vendorNo;
		this.shopTicketFl = shopTicketFl;
		this.salesOrgNm = salesOrgNm;
		this.militaryOrderFl = militaryOrderFl;
		this.workOrderStatusHsts = workOrderStatusHsts;
	}

	public BigDecimal getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(BigDecimal workOrderId) {
		this.workOrderId = workOrderId;
	}

	public SourceWorkOrder getSourceWorkOrder() {
		return this.sourceWorkOrder;
	}

	public void setSourceWorkOrder(SourceWorkOrder sourceWorkOrder) {
		this.sourceWorkOrder = sourceWorkOrder;
	}

	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getCustomerOwnedInventoryFl() {
		return this.customerOwnedInventoryFl;
	}

	public void setCustomerOwnedInventoryFl(String customerOwnedInventoryFl) {
		this.customerOwnedInventoryFl = customerOwnedInventoryFl;
	}

	public BigDecimal getFirstArticleSerialNo() {
		return this.firstArticleSerialNo;
	}

	public void setFirstArticleSerialNo(BigDecimal firstArticleSerialNo) {
		this.firstArticleSerialNo = firstArticleSerialNo;
	}

	public BigDecimal getOrderQt() {
		return this.orderQt;
	}

	public void setOrderQt(BigDecimal orderQt) {
		this.orderQt = orderQt;
	}

	public String getShipDateCommitToSalesFl() {
		return this.shipDateCommitToSalesFl;
	}

	public void setShipDateCommitToSalesFl(String shipDateCommitToSalesFl) {
		this.shipDateCommitToSalesFl = shipDateCommitToSalesFl;
	}

	public BigDecimal getSourcePartId() {
		return this.sourcePartId;
	}

	public void setSourcePartId(BigDecimal sourcePartId) {
		this.sourcePartId = sourcePartId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public BigDecimal getWorkOrderNo() {
		return this.workOrderNo;
	}

	public void setWorkOrderNo(BigDecimal workOrderNo) {
		this.workOrderNo = workOrderNo;
	}

	public BigDecimal getWorkOrderStatusId() {
		return this.workOrderStatusId;
	}

	public void setWorkOrderStatusId(BigDecimal workOrderStatusId) {
		this.workOrderStatusId = workOrderStatusId;
	}

	public String getExternalProblemFl() {
		return this.externalProblemFl;
	}

	public void setExternalProblemFl(String externalProblemFl) {
		this.externalProblemFl = externalProblemFl;
	}

	public BigDecimal getValueAddUnitCostAm() {
		return this.valueAddUnitCostAm;
	}

	public void setValueAddUnitCostAm(BigDecimal valueAddUnitCostAm) {
		this.valueAddUnitCostAm = valueAddUnitCostAm;
	}

	public String getCommentTx() {
		return this.commentTx;
	}

	public void setCommentTx(String commentTx) {
		this.commentTx = commentTx;
	}

	public String getCarrierServiceLevelCd() {
		return this.carrierServiceLevelCd;
	}

	public void setCarrierServiceLevelCd(String carrierServiceLevelCd) {
		this.carrierServiceLevelCd = carrierServiceLevelCd;
	}

	public String getCustomerPurchaseOrderNo() {
		return this.customerPurchaseOrderNo;
	}

	public void setCustomerPurchaseOrderNo(String customerPurchaseOrderNo) {
		this.customerPurchaseOrderNo = customerPurchaseOrderNo;
	}

	public String getMiscellaneousTx01() {
		return this.miscellaneousTx01;
	}

	public void setMiscellaneousTx01(String miscellaneousTx01) {
		this.miscellaneousTx01 = miscellaneousTx01;
	}

	public String getPartValueAddCd() {
		return this.partValueAddCd;
	}

	public void setPartValueAddCd(String partValueAddCd) {
		this.partValueAddCd = partValueAddCd;
	}

	public BigDecimal getShippedQt() {
		return this.shippedQt;
	}

	public void setShippedQt(BigDecimal shippedQt) {
		this.shippedQt = shippedQt;
	}

	public String getSpecialInstructionTx() {
		return this.specialInstructionTx;
	}

	public void setSpecialInstructionTx(String specialInstructionTx) {
		this.specialInstructionTx = specialInstructionTx;
	}

	public String getOnTimeDeliveryFl() {
		return this.onTimeDeliveryFl;
	}

	public void setOnTimeDeliveryFl(String onTimeDeliveryFl) {
		this.onTimeDeliveryFl = onTimeDeliveryFl;
	}

	public String getKitPartNo() {
		return this.kitPartNo;
	}

	public void setKitPartNo(String kitPartNo) {
		this.kitPartNo = kitPartNo;
	}

	public String getCutbackRequiredFl() {
		return this.cutbackRequiredFl;
	}

	public void setCutbackRequiredFl(String cutbackRequiredFl) {
		this.cutbackRequiredFl = cutbackRequiredFl;
	}

	public String getOrderLineNo() {
		return this.orderLineNo;
	}

	public void setOrderLineNo(String orderLineNo) {
		this.orderLineNo = orderLineNo;
	}

	public String getVendorNo() {
		return this.vendorNo;
	}

	public void setVendorNo(String vendorNo) {
		this.vendorNo = vendorNo;
	}

	public String getShopTicketFl() {
		return this.shopTicketFl;
	}

	public void setShopTicketFl(String shopTicketFl) {
		this.shopTicketFl = shopTicketFl;
	}

	public String getSalesOrgNm() {
		return this.salesOrgNm;
	}

	public void setSalesOrgNm(String salesOrgNm) {
		this.salesOrgNm = salesOrgNm;
	}

	public String getMilitaryOrderFl() {
		return this.militaryOrderFl;
	}

	public void setMilitaryOrderFl(String militaryOrderFl) {
		this.militaryOrderFl = militaryOrderFl;
	}

	public Set getWorkOrderStatusHsts() {
		return this.workOrderStatusHsts;
	}

	public void setWorkOrderStatusHsts(Set workOrderStatusHsts) {
		this.workOrderStatusHsts = workOrderStatusHsts;
	}

}
