package com.avnet.alapps.model.gsfcreport;

// Generated Aug 31, 2015 4:15:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * WorkOrderStatusHst generated by hbm2java
 */
public class WorkOrderStatusHst implements java.io.Serializable {

	private BigDecimal workOrderStatusHstId;
	private WorkOrder workOrder;
	private Date createDt;
	private BigDecimal createUserId;
	private Date effectiveFromDt;
	private Date effectiveThruDt;
	private Date updateDt;
	private BigDecimal updateUserId;
	private BigDecimal workOrderStatusId;

	public WorkOrderStatusHst() {
	}

	public WorkOrderStatusHst(BigDecimal workOrderStatusHstId,
			WorkOrder workOrder, Date createDt, BigDecimal createUserId,
			Date effectiveFromDt, Date updateDt, BigDecimal updateUserId,
			BigDecimal workOrderStatusId) {
		this.workOrderStatusHstId = workOrderStatusHstId;
		this.workOrder = workOrder;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.effectiveFromDt = effectiveFromDt;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.workOrderStatusId = workOrderStatusId;
	}

	public WorkOrderStatusHst(BigDecimal workOrderStatusHstId,
			WorkOrder workOrder, Date createDt, BigDecimal createUserId,
			Date effectiveFromDt, Date effectiveThruDt, Date updateDt,
			BigDecimal updateUserId, BigDecimal workOrderStatusId) {
		this.workOrderStatusHstId = workOrderStatusHstId;
		this.workOrder = workOrder;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.effectiveFromDt = effectiveFromDt;
		this.effectiveThruDt = effectiveThruDt;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.workOrderStatusId = workOrderStatusId;
	}

	public BigDecimal getWorkOrderStatusHstId() {
		return this.workOrderStatusHstId;
	}

	public void setWorkOrderStatusHstId(BigDecimal workOrderStatusHstId) {
		this.workOrderStatusHstId = workOrderStatusHstId;
	}

	public WorkOrder getWorkOrder() {
		return this.workOrder;
	}

	public void setWorkOrder(WorkOrder workOrder) {
		this.workOrder = workOrder;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public Date getEffectiveFromDt() {
		return this.effectiveFromDt;
	}

	public void setEffectiveFromDt(Date effectiveFromDt) {
		this.effectiveFromDt = effectiveFromDt;
	}

	public Date getEffectiveThruDt() {
		return this.effectiveThruDt;
	}

	public void setEffectiveThruDt(Date effectiveThruDt) {
		this.effectiveThruDt = effectiveThruDt;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public BigDecimal getWorkOrderStatusId() {
		return this.workOrderStatusId;
	}

	public void setWorkOrderStatusId(BigDecimal workOrderStatusId) {
		this.workOrderStatusId = workOrderStatusId;
	}

}
