package com.avnet.alapps.model.alapps;

// Generated Aug 8, 2016 1:52:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstCompTypeAttr generated by hbm2java
 */
public class AstCompTypeAttr implements java.io.Serializable {

	private BigDecimal compTypeAttrId;
	private AstDataType astDataType;
	private AstDataSource astDataSource;
	private AstCompType astCompType;
	private String attrNm;
	private String attrDs;
	private String xmlTag;
	private String activeFl;
	private String keyFl;
	private Date createDt;
	private Date updateDt;
	private String createUsrId;
	private String updateUsrId;
	private String editableFl;
	private Set astPartAttrs = new HashSet(0);

	public AstCompTypeAttr() {
	}

	public AstCompTypeAttr(BigDecimal compTypeAttrId, AstDataType astDataType,
			AstDataSource astDataSource, AstCompType astCompType,
			String attrNm, String attrDs, String activeFl) {
		this.compTypeAttrId = compTypeAttrId;
		this.astDataType = astDataType;
		this.astDataSource = astDataSource;
		this.astCompType = astCompType;
		this.attrNm = attrNm;
		this.attrDs = attrDs;
		this.activeFl = activeFl;
	}

	public AstCompTypeAttr(BigDecimal compTypeAttrId, AstDataType astDataType,
			AstDataSource astDataSource, AstCompType astCompType,
			String attrNm, String attrDs, String xmlTag, String activeFl,
			String keyFl, Date createDt, Date updateDt, String createUsrId,
			String updateUsrId, String editableFl, Set astPartAttrs) {
		this.compTypeAttrId = compTypeAttrId;
		this.astDataType = astDataType;
		this.astDataSource = astDataSource;
		this.astCompType = astCompType;
		this.attrNm = attrNm;
		this.attrDs = attrDs;
		this.xmlTag = xmlTag;
		this.activeFl = activeFl;
		this.keyFl = keyFl;
		this.createDt = createDt;
		this.updateDt = updateDt;
		this.createUsrId = createUsrId;
		this.updateUsrId = updateUsrId;
		this.editableFl = editableFl;
		this.astPartAttrs = astPartAttrs;
	}

	public BigDecimal getCompTypeAttrId() {
		return this.compTypeAttrId;
	}

	public void setCompTypeAttrId(BigDecimal compTypeAttrId) {
		this.compTypeAttrId = compTypeAttrId;
	}

	public AstDataType getAstDataType() {
		return this.astDataType;
	}

	public void setAstDataType(AstDataType astDataType) {
		this.astDataType = astDataType;
	}

	public AstDataSource getAstDataSource() {
		return this.astDataSource;
	}

	public void setAstDataSource(AstDataSource astDataSource) {
		this.astDataSource = astDataSource;
	}

	public AstCompType getAstCompType() {
		return this.astCompType;
	}

	public void setAstCompType(AstCompType astCompType) {
		this.astCompType = astCompType;
	}

	public String getAttrNm() {
		return this.attrNm;
	}

	public void setAttrNm(String attrNm) {
		this.attrNm = attrNm;
	}

	public String getAttrDs() {
		return this.attrDs;
	}

	public void setAttrDs(String attrDs) {
		this.attrDs = attrDs;
	}

	public String getXmlTag() {
		return this.xmlTag;
	}

	public void setXmlTag(String xmlTag) {
		this.xmlTag = xmlTag;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public String getKeyFl() {
		return this.keyFl;
	}

	public void setKeyFl(String keyFl) {
		this.keyFl = keyFl;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public String getCreateUsrId() {
		return this.createUsrId;
	}

	public void setCreateUsrId(String createUsrId) {
		this.createUsrId = createUsrId;
	}

	public String getUpdateUsrId() {
		return this.updateUsrId;
	}

	public void setUpdateUsrId(String updateUsrId) {
		this.updateUsrId = updateUsrId;
	}

	public String getEditableFl() {
		return this.editableFl;
	}

	public void setEditableFl(String editableFl) {
		this.editableFl = editableFl;
	}

	public Set getAstPartAttrs() {
		return this.astPartAttrs;
	}

	public void setAstPartAttrs(Set astPartAttrs) {
		this.astPartAttrs = astPartAttrs;
	}

}
