package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstCompType generated by hbm2java
 */
public class AstCompType implements java.io.Serializable {

	private BigDecimal compTypeId;
	private AstCompType astCompType;
	private String typeNm;
	private String typeDs;
	private String xmlTag;
	private String activeFl;
	private Date createDt;
	private String createUsrId;
	private Date updateDt;
	private String updateUsrId;
	private Set astCompTypeAttrs = new HashSet(0);
	private Set astParts = new HashSet(0);
	private Set astSubPartCtrls = new HashSet(0);
	private Set astCompTypes = new HashSet(0);

	public AstCompType() {
	}

	public AstCompType(BigDecimal compTypeId, String typeNm, String typeDs,
			String activeFl) {
		this.compTypeId = compTypeId;
		this.typeNm = typeNm;
		this.typeDs = typeDs;
		this.activeFl = activeFl;
	}

	public AstCompType(BigDecimal compTypeId, AstCompType astCompType,
			String typeNm, String typeDs, String xmlTag, String activeFl,
			Date createDt, String createUsrId, Date updateDt,
			String updateUsrId, Set astCompTypeAttrs, Set astParts,
			Set astSubPartCtrls, Set astCompTypes) {
		this.compTypeId = compTypeId;
		this.astCompType = astCompType;
		this.typeNm = typeNm;
		this.typeDs = typeDs;
		this.xmlTag = xmlTag;
		this.activeFl = activeFl;
		this.createDt = createDt;
		this.createUsrId = createUsrId;
		this.updateDt = updateDt;
		this.updateUsrId = updateUsrId;
		this.astCompTypeAttrs = astCompTypeAttrs;
		this.astParts = astParts;
		this.astSubPartCtrls = astSubPartCtrls;
		this.astCompTypes = astCompTypes;
	}

	public BigDecimal getCompTypeId() {
		return this.compTypeId;
	}

	public void setCompTypeId(BigDecimal compTypeId) {
		this.compTypeId = compTypeId;
	}

	public AstCompType getAstCompType() {
		return this.astCompType;
	}

	public void setAstCompType(AstCompType astCompType) {
		this.astCompType = astCompType;
	}

	public String getTypeNm() {
		return this.typeNm;
	}

	public void setTypeNm(String typeNm) {
		this.typeNm = typeNm;
	}

	public String getTypeDs() {
		return this.typeDs;
	}

	public void setTypeDs(String typeDs) {
		this.typeDs = typeDs;
	}

	public String getXmlTag() {
		return this.xmlTag;
	}

	public void setXmlTag(String xmlTag) {
		this.xmlTag = xmlTag;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getCreateUsrId() {
		return this.createUsrId;
	}

	public void setCreateUsrId(String createUsrId) {
		this.createUsrId = createUsrId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public String getUpdateUsrId() {
		return this.updateUsrId;
	}

	public void setUpdateUsrId(String updateUsrId) {
		this.updateUsrId = updateUsrId;
	}

	public Set getAstCompTypeAttrs() {
		return this.astCompTypeAttrs;
	}

	public void setAstCompTypeAttrs(Set astCompTypeAttrs) {
		this.astCompTypeAttrs = astCompTypeAttrs;
	}

	public Set getAstParts() {
		return this.astParts;
	}

	public void setAstParts(Set astParts) {
		this.astParts = astParts;
	}

	public Set getAstSubPartCtrls() {
		return this.astSubPartCtrls;
	}

	public void setAstSubPartCtrls(Set astSubPartCtrls) {
		this.astSubPartCtrls = astSubPartCtrls;
	}

	public Set getAstCompTypes() {
		return this.astCompTypes;
	}

	public void setAstCompTypes(Set astCompTypes) {
		this.astCompTypes = astCompTypes;
	}

}
