package com.avnet.alapps.model.alapps;

// Generated Nov 5, 2015 12:40:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AstDataSource generated by hbm2java
 */
public class AstDataSource implements java.io.Serializable {

	private BigDecimal dataSourceId;
	private String sourceNm;
	private String sourceDs;
	private Set astCompTypeAttrs = new HashSet(0);

	public AstDataSource() {
	}

	public AstDataSource(BigDecimal dataSourceId, String sourceNm,
			String sourceDs) {
		this.dataSourceId = dataSourceId;
		this.sourceNm = sourceNm;
		this.sourceDs = sourceDs;
	}

	public AstDataSource(BigDecimal dataSourceId, String sourceNm,
			String sourceDs, Set astCompTypeAttrs) {
		this.dataSourceId = dataSourceId;
		this.sourceNm = sourceNm;
		this.sourceDs = sourceDs;
		this.astCompTypeAttrs = astCompTypeAttrs;
	}

	public BigDecimal getDataSourceId() {
		return this.dataSourceId;
	}

	public void setDataSourceId(BigDecimal dataSourceId) {
		this.dataSourceId = dataSourceId;
	}

	public String getSourceNm() {
		return this.sourceNm;
	}

	public void setSourceNm(String sourceNm) {
		this.sourceNm = sourceNm;
	}

	public String getSourceDs() {
		return this.sourceDs;
	}

	public void setSourceDs(String sourceDs) {
		this.sourceDs = sourceDs;
	}

	public Set getAstCompTypeAttrs() {
		return this.astCompTypeAttrs;
	}

	public void setAstCompTypeAttrs(Set astCompTypeAttrs) {
		this.astCompTypeAttrs = astCompTypeAttrs;
	}

}
