package com.avnet.alapps.model.alapps;

// Generated Nov 5, 2015 12:40:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AstDataType generated by hbm2java
 */
public class AstDataType implements java.io.Serializable {

	private BigDecimal dataTypeId;
	private String typeNm;
	private Set astCompTypeAttrs = new HashSet(0);

	public AstDataType() {
	}

	public AstDataType(BigDecimal dataTypeId, String typeNm) {
		this.dataTypeId = dataTypeId;
		this.typeNm = typeNm;
	}

	public AstDataType(BigDecimal dataTypeId, String typeNm,
			Set astCompTypeAttrs) {
		this.dataTypeId = dataTypeId;
		this.typeNm = typeNm;
		this.astCompTypeAttrs = astCompTypeAttrs;
	}

	public BigDecimal getDataTypeId() {
		return this.dataTypeId;
	}

	public void setDataTypeId(BigDecimal dataTypeId) {
		this.dataTypeId = dataTypeId;
	}

	public String getTypeNm() {
		return this.typeNm;
	}

	public void setTypeNm(String typeNm) {
		this.typeNm = typeNm;
	}

	public Set getAstCompTypeAttrs() {
		return this.astCompTypeAttrs;
	}

	public void setAstCompTypeAttrs(Set astCompTypeAttrs) {
		this.astCompTypeAttrs = astCompTypeAttrs;
	}

}
