package com.avnet.alapps.model.alapps;

// Generated Aug 17, 2016 2:43:00 PM by Hibernate Tools 4.3.1

/**
 * AstOrderInfoId generated by hbm2java
 */
public class AstOrderInfoId implements java.io.Serializable {

	private String icn;
	private String scn;

	public AstOrderInfoId() {
	}

	public AstOrderInfoId(String icn, String scn) {
		this.icn = icn;
		this.scn = scn;
	}

	public String getIcn() {
		return this.icn;
	}

	public void setIcn(String icn) {
		this.icn = icn;
	}

	public String getScn() {
		return this.scn;
	}

	public void setScn(String scn) {
		this.scn = scn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AstOrderInfoId))
			return false;
		AstOrderInfoId castOther = (AstOrderInfoId) other;

		return ((this.getIcn() == castOther.getIcn()) || (this.getIcn() != null
				&& castOther.getIcn() != null && this.getIcn().equals(
				castOther.getIcn())))
				&& ((this.getScn() == castOther.getScn()) || (this.getScn() != null
						&& castOther.getScn() != null && this.getScn().equals(
						castOther.getScn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIcn() == null ? 0 : this.getIcn().hashCode());
		result = 37 * result
				+ (getScn() == null ? 0 : this.getScn().hashCode());
		return result;
	}

}
