package com.avnet.alapps.model.alapps;

// Generated Aug 17, 2016 2:43:00 PM by Hibernate Tools 4.3.1

/**
 * AstOrderInfoWaybillId generated by hbm2java
 */
public class AstOrderInfoWaybillId implements java.io.Serializable {

	private String scn;
	private String sapDelivery;

	public AstOrderInfoWaybillId() {
	}

	public AstOrderInfoWaybillId(String scn, String sapDelivery) {
		this.scn = scn;
		this.sapDelivery = sapDelivery;
	}

	public String getScn() {
		return this.scn;
	}

	public void setScn(String scn) {
		this.scn = scn;
	}

	public String getSapDelivery() {
		return this.sapDelivery;
	}

	public void setSapDelivery(String sapDelivery) {
		this.sapDelivery = sapDelivery;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AstOrderInfoWaybillId))
			return false;
		AstOrderInfoWaybillId castOther = (AstOrderInfoWaybillId) other;

		return ((this.getScn() == castOther.getScn()) || (this.getScn() != null
				&& castOther.getScn() != null && this.getScn().equals(
				castOther.getScn())))
				&& ((this.getSapDelivery() == castOther.getSapDelivery()) || (this
						.getSapDelivery() != null
						&& castOther.getSapDelivery() != null && this
						.getSapDelivery().equals(castOther.getSapDelivery())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getScn() == null ? 0 : this.getScn().hashCode());
		result = 37
				* result
				+ (getSapDelivery() == null ? 0 : this.getSapDelivery()
						.hashCode());
		return result;
	}

}
