package com.avnet.alapps.model.alapps;

// Generated Aug 17, 2016 2:43:00 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AstOrderInfoWaybill generated by hbm2java
 */
public class AstOrderInfoWaybill implements java.io.Serializable {

	private AstOrderInfoWaybillId id;
	private String carrierName;
	private String waybill;
	private Date shipDt;

	public AstOrderInfoWaybill() {
	}

	public AstOrderInfoWaybill(AstOrderInfoWaybillId id) {
		this.id = id;
	}

	public AstOrderInfoWaybill(AstOrderInfoWaybillId id, String carrierName,
			String waybill, Date shipDt) {
		this.id = id;
		this.carrierName = carrierName;
		this.waybill = waybill;
		this.shipDt = shipDt;
	}

	public AstOrderInfoWaybillId getId() {
		return this.id;
	}

	public void setId(AstOrderInfoWaybillId id) {
		this.id = id;
	}

	public String getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

	public String getWaybill() {
		return this.waybill;
	}

	public void setWaybill(String waybill) {
		this.waybill = waybill;
	}

	public Date getShipDt() {
		return this.shipDt;
	}

	public void setShipDt(Date shipDt) {
		this.shipDt = shipDt;
	}

}
