package com.avnet.alapps.model.alapps;

// Generated Aug 17, 2016 2:43:00 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * AstOrderInfo generated by hbm2java
 */
public class AstOrderInfo implements java.io.Serializable {

	private AstOrderInfoId id;
	private String shiptoName;
	private String shiptoName2;
	private String shiptoAddr1;
	private String shiptoAddr2;
	private String shiptoAddr3;
	private String shiptoCity;
	private String shiptoState;
	private String shiptoCountry;
	private String shiptoPostalcode;
	private String shiptoContactName;
	private String shiptoContactPhone;
	private String customerPo;
	private String customerOrder;
	private BigDecimal updateCount;
	private String shipviaName;

	public AstOrderInfo() {
	}

	public AstOrderInfo(AstOrderInfoId id) {
		this.id = id;
	}

	public AstOrderInfo(AstOrderInfoId id, String shiptoName,
			String shiptoName2, String shiptoAddr1, String shiptoAddr2,
			String shiptoAddr3, String shiptoCity, String shiptoState,
			String shiptoCountry, String shiptoPostalcode,
			String shiptoContactName, String shiptoContactPhone,
			String customerPo, String customerOrder, BigDecimal updateCount,
			String shipviaName) {
		this.id = id;
		this.shiptoName = shiptoName;
		this.shiptoName2 = shiptoName2;
		this.shiptoAddr1 = shiptoAddr1;
		this.shiptoAddr2 = shiptoAddr2;
		this.shiptoAddr3 = shiptoAddr3;
		this.shiptoCity = shiptoCity;
		this.shiptoState = shiptoState;
		this.shiptoCountry = shiptoCountry;
		this.shiptoPostalcode = shiptoPostalcode;
		this.shiptoContactName = shiptoContactName;
		this.shiptoContactPhone = shiptoContactPhone;
		this.customerPo = customerPo;
		this.customerOrder = customerOrder;
		this.updateCount = updateCount;
		this.shipviaName = shipviaName;
	}

	public AstOrderInfoId getId() {
		return this.id;
	}

	public void setId(AstOrderInfoId id) {
		this.id = id;
	}

	public String getShiptoName() {
		return this.shiptoName;
	}

	public void setShiptoName(String shiptoName) {
		this.shiptoName = shiptoName;
	}

	public String getShiptoName2() {
		return this.shiptoName2;
	}

	public void setShiptoName2(String shiptoName2) {
		this.shiptoName2 = shiptoName2;
	}

	public String getShiptoAddr1() {
		return this.shiptoAddr1;
	}

	public void setShiptoAddr1(String shiptoAddr1) {
		this.shiptoAddr1 = shiptoAddr1;
	}

	public String getShiptoAddr2() {
		return this.shiptoAddr2;
	}

	public void setShiptoAddr2(String shiptoAddr2) {
		this.shiptoAddr2 = shiptoAddr2;
	}

	public String getShiptoAddr3() {
		return this.shiptoAddr3;
	}

	public void setShiptoAddr3(String shiptoAddr3) {
		this.shiptoAddr3 = shiptoAddr3;
	}

	public String getShiptoCity() {
		return this.shiptoCity;
	}

	public void setShiptoCity(String shiptoCity) {
		this.shiptoCity = shiptoCity;
	}

	public String getShiptoState() {
		return this.shiptoState;
	}

	public void setShiptoState(String shiptoState) {
		this.shiptoState = shiptoState;
	}

	public String getShiptoCountry() {
		return this.shiptoCountry;
	}

	public void setShiptoCountry(String shiptoCountry) {
		this.shiptoCountry = shiptoCountry;
	}

	public String getShiptoPostalcode() {
		return this.shiptoPostalcode;
	}

	public void setShiptoPostalcode(String shiptoPostalcode) {
		this.shiptoPostalcode = shiptoPostalcode;
	}

	public String getShiptoContactName() {
		return this.shiptoContactName;
	}

	public void setShiptoContactName(String shiptoContactName) {
		this.shiptoContactName = shiptoContactName;
	}

	public String getShiptoContactPhone() {
		return this.shiptoContactPhone;
	}

	public void setShiptoContactPhone(String shiptoContactPhone) {
		this.shiptoContactPhone = shiptoContactPhone;
	}

	public String getCustomerPo() {
		return this.customerPo;
	}

	public void setCustomerPo(String customerPo) {
		this.customerPo = customerPo;
	}

	public String getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(String customerOrder) {
		this.customerOrder = customerOrder;
	}

	public BigDecimal getUpdateCount() {
		return this.updateCount;
	}

	public void setUpdateCount(BigDecimal updateCount) {
		this.updateCount = updateCount;
	}

	public String getShipviaName() {
		return this.shipviaName;
	}

	public void setShipviaName(String shipviaName) {
		this.shipviaName = shipviaName;
	}

}
