package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstPart generated by hbm2java
 */
public class AstPart implements java.io.Serializable {

	private BigDecimal partId;
	private AstCompType astCompType;
	private String activeFl;
	private String keyValue;
	private Date createDt;
	private String createUsrId;
	private Date updateDt;
	private String updateUsrId;
	private Set astPartAsms = new HashSet(0);
	private Set astPartAttrs = new HashSet(0);
	private AstSubPartCtrl astSubPartCtrl;

	public AstPart() {
	}

	public AstPart(BigDecimal partId, AstCompType astCompType, String activeFl,
			String keyValue) {
		this.partId = partId;
		this.astCompType = astCompType;
		this.activeFl = activeFl;
		this.keyValue = keyValue;
	}

	public AstPart(BigDecimal partId, AstCompType astCompType, String activeFl,
			String keyValue, Date createDt, String createUsrId, Date updateDt,
			String updateUsrId, Set astPartAsms, Set astPartAttrs,
			AstSubPartCtrl astSubPartCtrl) {
		this.partId = partId;
		this.astCompType = astCompType;
		this.activeFl = activeFl;
		this.keyValue = keyValue;
		this.createDt = createDt;
		this.createUsrId = createUsrId;
		this.updateDt = updateDt;
		this.updateUsrId = updateUsrId;
		this.astPartAsms = astPartAsms;
		this.astPartAttrs = astPartAttrs;
		this.astSubPartCtrl = astSubPartCtrl;
	}

	public BigDecimal getPartId() {
		return this.partId;
	}

	public void setPartId(BigDecimal partId) {
		this.partId = partId;
	}

	public AstCompType getAstCompType() {
		return this.astCompType;
	}

	public void setAstCompType(AstCompType astCompType) {
		this.astCompType = astCompType;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getCreateUsrId() {
		return this.createUsrId;
	}

	public void setCreateUsrId(String createUsrId) {
		this.createUsrId = createUsrId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public String getUpdateUsrId() {
		return this.updateUsrId;
	}

	public void setUpdateUsrId(String updateUsrId) {
		this.updateUsrId = updateUsrId;
	}

	public Set getAstPartAsms() {
		return this.astPartAsms;
	}

	public void setAstPartAsms(Set astPartAsms) {
		this.astPartAsms = astPartAsms;
	}

	public Set getAstPartAttrs() {
		return this.astPartAttrs;
	}

	public void setAstPartAttrs(Set astPartAttrs) {
		this.astPartAttrs = astPartAttrs;
	}

	public AstSubPartCtrl getAstSubPartCtrl() {
		return this.astSubPartCtrl;
	}

	public void setAstSubPartCtrl(AstSubPartCtrl astSubPartCtrl) {
		this.astSubPartCtrl = astSubPartCtrl;
	}

}
