package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstPartAttr generated by hbm2java
 */
public class AstPartAttr implements java.io.Serializable {

	private BigDecimal partAttrId;
	private AstPart astPart;
	private AstCompTypeAttr astCompTypeAttr;
	private String valueTx;
	private Date createDt;
	private String createUsrId;
	private Date updateDt;
	private String updateUsrId;
	private Set astPartAsmAttrs = new HashSet(0);

	public AstPartAttr() {
	}

	public AstPartAttr(BigDecimal partAttrId, AstPart astPart,
			AstCompTypeAttr astCompTypeAttr) {
		this.partAttrId = partAttrId;
		this.astPart = astPart;
		this.astCompTypeAttr = astCompTypeAttr;
	}

	public AstPartAttr(BigDecimal partAttrId, AstPart astPart,
			AstCompTypeAttr astCompTypeAttr, String valueTx, Date createDt,
			String createUsrId, Date updateDt, String updateUsrId,
			Set astPartAsmAttrs) {
		this.partAttrId = partAttrId;
		this.astPart = astPart;
		this.astCompTypeAttr = astCompTypeAttr;
		this.valueTx = valueTx;
		this.createDt = createDt;
		this.createUsrId = createUsrId;
		this.updateDt = updateDt;
		this.updateUsrId = updateUsrId;
		this.astPartAsmAttrs = astPartAsmAttrs;
	}

	public BigDecimal getPartAttrId() {
		return this.partAttrId;
	}

	public void setPartAttrId(BigDecimal partAttrId) {
		this.partAttrId = partAttrId;
	}

	public AstPart getAstPart() {
		return this.astPart;
	}

	public void setAstPart(AstPart astPart) {
		this.astPart = astPart;
	}

	public AstCompTypeAttr getAstCompTypeAttr() {
		return this.astCompTypeAttr;
	}

	public void setAstCompTypeAttr(AstCompTypeAttr astCompTypeAttr) {
		this.astCompTypeAttr = astCompTypeAttr;
	}

	public String getValueTx() {
		return this.valueTx;
	}

	public void setValueTx(String valueTx) {
		this.valueTx = valueTx;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getCreateUsrId() {
		return this.createUsrId;
	}

	public void setCreateUsrId(String createUsrId) {
		this.createUsrId = createUsrId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public String getUpdateUsrId() {
		return this.updateUsrId;
	}

	public void setUpdateUsrId(String updateUsrId) {
		this.updateUsrId = updateUsrId;
	}

	public Set getAstPartAsmAttrs() {
		return this.astPartAsmAttrs;
	}

	public void setAstPartAsmAttrs(Set astPartAsmAttrs) {
		this.astPartAsmAttrs = astPartAsmAttrs;
	}

}
