package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AstPartAsmAttr generated by hbm2java
 */
public class AstPartAsmAttr implements java.io.Serializable {

	private BigDecimal partAsmAttrId;
	private AstPartAsm astPartAsm;
	private AstPartAttr astPartAttr;
	private String valueTx;
	private String createUsrId;
	private Date createDt;
	private Date updateDt;
	private String updateUsrId;

	public AstPartAsmAttr() {
	}

	public AstPartAsmAttr(BigDecimal partAsmAttrId, AstPartAttr astPartAttr) {
		this.partAsmAttrId = partAsmAttrId;
		this.astPartAttr = astPartAttr;
	}

	public AstPartAsmAttr(BigDecimal partAsmAttrId, AstPartAsm astPartAsm,
			AstPartAttr astPartAttr, String valueTx, String createUsrId,
			Date createDt, Date updateDt, String updateUsrId) {
		this.partAsmAttrId = partAsmAttrId;
		this.astPartAsm = astPartAsm;
		this.astPartAttr = astPartAttr;
		this.valueTx = valueTx;
		this.createUsrId = createUsrId;
		this.createDt = createDt;
		this.updateDt = updateDt;
		this.updateUsrId = updateUsrId;
	}

	public BigDecimal getPartAsmAttrId() {
		return this.partAsmAttrId;
	}

	public void setPartAsmAttrId(BigDecimal partAsmAttrId) {
		this.partAsmAttrId = partAsmAttrId;
	}

	public AstPartAsm getAstPartAsm() {
		return this.astPartAsm;
	}

	public void setAstPartAsm(AstPartAsm astPartAsm) {
		this.astPartAsm = astPartAsm;
	}

	public AstPartAttr getAstPartAttr() {
		return this.astPartAttr;
	}

	public void setAstPartAttr(AstPartAttr astPartAttr) {
		this.astPartAttr = astPartAttr;
	}

	public String getValueTx() {
		return this.valueTx;
	}

	public void setValueTx(String valueTx) {
		this.valueTx = valueTx;
	}

	public String getCreateUsrId() {
		return this.createUsrId;
	}

	public void setCreateUsrId(String createUsrId) {
		this.createUsrId = createUsrId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public String getUpdateUsrId() {
		return this.updateUsrId;
	}

	public void setUpdateUsrId(String updateUsrId) {
		this.updateUsrId = updateUsrId;
	}

}
