package com.avnet.alapps.model.alapps;

// Generated Nov 5, 2015 12:40:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * AstSubPartCtrl generated by hbm2java
 */
public class AstSubPartCtrl implements java.io.Serializable {

	private BigDecimal partId;
	private AstCompType astCompType;
	private AstPart astPart;
	private BigDecimal minOccurrence;
	private BigDecimal maxOccurrence;

	public AstSubPartCtrl() {
	}

	public AstSubPartCtrl(AstCompType astCompType, AstPart astPart,
			BigDecimal minOccurrence, BigDecimal maxOccurrence) {
		this.astCompType = astCompType;
		this.astPart = astPart;
		this.minOccurrence = minOccurrence;
		this.maxOccurrence = maxOccurrence;
	}

	public BigDecimal getPartId() {
		return this.partId;
	}

	public void setPartId(BigDecimal partId) {
		this.partId = partId;
	}

	public AstCompType getAstCompType() {
		return this.astCompType;
	}

	public void setAstCompType(AstCompType astCompType) {
		this.astCompType = astCompType;
	}

	public AstPart getAstPart() {
		return this.astPart;
	}

	public void setAstPart(AstPart astPart) {
		this.astPart = astPart;
	}

	public BigDecimal getMinOccurrence() {
		return this.minOccurrence;
	}

	public void setMinOccurrence(BigDecimal minOccurrence) {
		this.minOccurrence = minOccurrence;
	}

	public BigDecimal getMaxOccurrence() {
		return this.maxOccurrence;
	}

	public void setMaxOccurrence(BigDecimal maxOccurrence) {
		this.maxOccurrence = maxOccurrence;
	}

}
