package com.avnet.alapps.model.alapps;

// Generated Nov 5, 2015 4:46:08 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AstTestResultCode generated by hbm2java
 */
public class AstTestResultCode implements java.io.Serializable {

	private BigDecimal testResultCodeId;
	private String codeNm;
	private String codeDs;
	private Set astTestResults = new HashSet(0);
	private Set astTestResultItems = new HashSet(0);

	public AstTestResultCode() {
	}

	public AstTestResultCode(BigDecimal testResultCodeId, String codeNm,
			String codeDs) {
		this.testResultCodeId = testResultCodeId;
		this.codeNm = codeNm;
		this.codeDs = codeDs;
	}

	public AstTestResultCode(BigDecimal testResultCodeId, String codeNm,
			String codeDs, Set astTestResults, Set astTestResultItems) {
		this.testResultCodeId = testResultCodeId;
		this.codeNm = codeNm;
		this.codeDs = codeDs;
		this.astTestResults = astTestResults;
		this.astTestResultItems = astTestResultItems;
	}

	public BigDecimal getTestResultCodeId() {
		return this.testResultCodeId;
	}

	public void setTestResultCodeId(BigDecimal testResultCodeId) {
		this.testResultCodeId = testResultCodeId;
	}

	public String getCodeNm() {
		return this.codeNm;
	}

	public void setCodeNm(String codeNm) {
		this.codeNm = codeNm;
	}

	public String getCodeDs() {
		return this.codeDs;
	}

	public void setCodeDs(String codeDs) {
		this.codeDs = codeDs;
	}

	public Set getAstTestResults() {
		return this.astTestResults;
	}

	public void setAstTestResults(Set astTestResults) {
		this.astTestResults = astTestResults;
	}

	public Set getAstTestResultItems() {
		return this.astTestResultItems;
	}

	public void setAstTestResultItems(Set astTestResultItems) {
		this.astTestResultItems = astTestResultItems;
	}

}
