package com.avnet.alapps.model.alapps;

// Generated Dec 18, 2015 1:28:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AstTempBom generated by hbm2java
 */
public class AstTempBom implements java.io.Serializable {

	private BigDecimal bomId;
	private String partNum;
	private String serialNum;
	private BigDecimal parentBomId;
	private String icn;
	private Set astTempBomParts = new HashSet(0);

	public AstTempBom() {
	}

	public AstTempBom(BigDecimal bomId, String icn) {
		this.bomId = bomId;
		this.icn = icn;
	}

	public AstTempBom(BigDecimal bomId, String partNum, String serialNum,
			BigDecimal parentBomId, String icn, Set astTempBomParts) {
		this.bomId = bomId;
		this.partNum = partNum;
		this.serialNum = serialNum;
		this.parentBomId = parentBomId;
		this.icn = icn;
		this.astTempBomParts = astTempBomParts;
	}

	public BigDecimal getBomId() {
		return this.bomId;
	}

	public void setBomId(BigDecimal bomId) {
		this.bomId = bomId;
	}

	public String getPartNum() {
		return this.partNum;
	}

	public void setPartNum(String partNum) {
		this.partNum = partNum;
	}

	public String getSerialNum() {
		return this.serialNum;
	}

	public void setSerialNum(String serialNum) {
		this.serialNum = serialNum;
	}

	public BigDecimal getParentBomId() {
		return this.parentBomId;
	}

	public void setParentBomId(BigDecimal parentBomId) {
		this.parentBomId = parentBomId;
	}

	public String getIcn() {
		return this.icn;
	}

	public void setIcn(String icn) {
		this.icn = icn;
	}

	public Set getAstTempBomParts() {
		return this.astTempBomParts;
	}

	public void setAstTempBomParts(Set astTempBomParts) {
		this.astTempBomParts = astTempBomParts;
	}

}
