package com.avnet.alapps.model.alapps;

// Generated Nov 5, 2015 12:40:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * AstTempBomPart generated by hbm2java
 */
public class AstTempBomPart implements java.io.Serializable {

	private BigDecimal partId;
	private AstTempBom astTempBom;
	private String partNum;
	private String serialNum;
	private String partDs;

	public AstTempBomPart() {
	}

	public AstTempBomPart(BigDecimal partId, AstTempBom astTempBom) {
		this.partId = partId;
		this.astTempBom = astTempBom;
	}

	public AstTempBomPart(BigDecimal partId, AstTempBom astTempBom,
			String partNum, String serialNum, String partDs) {
		this.partId = partId;
		this.astTempBom = astTempBom;
		this.partNum = partNum;
		this.serialNum = serialNum;
		this.partDs = partDs;
	}

	public BigDecimal getPartId() {
		return this.partId;
	}

	public void setPartId(BigDecimal partId) {
		this.partId = partId;
	}

	public AstTempBom getAstTempBom() {
		return this.astTempBom;
	}

	public void setAstTempBom(AstTempBom astTempBom) {
		this.astTempBom = astTempBom;
	}

	public String getPartNum() {
		return this.partNum;
	}

	public void setPartNum(String partNum) {
		this.partNum = partNum;
	}

	public String getSerialNum() {
		return this.serialNum;
	}

	public void setSerialNum(String serialNum) {
		this.serialNum = serialNum;
	}

	public String getPartDs() {
		return this.partDs;
	}

	public void setPartDs(String partDs) {
		this.partDs = partDs;
	}

}
