package com.avnet.alapps.model.alapps;

// Generated Nov 12, 2015 4:23:01 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstTestResult generated by hbm2java
 */
public class MinAstTestResult implements java.io.Serializable {

	private BigDecimal testResultId;
	private AstTestResultCode astTestResultCode;
	private MinAstPartAsm astPartAsm;
	private String testStation;
	private String testerName;
	private String operatorId;
	private Date createDt;
	private String testSystemNm;
	private Set astTestResultItems = new HashSet(0);

	public MinAstTestResult() {
	}

	public MinAstTestResult(BigDecimal testResultId,
			AstTestResultCode astTestResultCode, Date createDt) {
		this.testResultId = testResultId;
		this.astTestResultCode = astTestResultCode;
		this.createDt = createDt;
	}

	public MinAstTestResult(BigDecimal testResultId,
			AstTestResultCode astTestResultCode, MinAstPartAsm astPartAsm,
			String testStation, String testerName, String operatorId,
			Date createDt, String testSystemNm, Set astTestResultItems) {
		this.testResultId = testResultId;
		this.astTestResultCode = astTestResultCode;
		this.astPartAsm = astPartAsm;
		this.testStation = testStation;
		this.testerName = testerName;
		this.operatorId = operatorId;
		this.createDt = createDt;
		this.testSystemNm = testSystemNm;
		this.astTestResultItems = astTestResultItems;
	}

	public BigDecimal getTestResultId() {
		return this.testResultId;
	}

	public void setTestResultId(BigDecimal testResultId) {
		this.testResultId = testResultId;
	}

	public AstTestResultCode getAstTestResultCode() {
		return this.astTestResultCode;
	}

	public void setAstTestResultCode(AstTestResultCode astTestResultCode) {
		this.astTestResultCode = astTestResultCode;
	}

	public MinAstPartAsm getAstPartAsm() {
		return this.astPartAsm;
	}

	public void setAstPartAsm(MinAstPartAsm astPartAsm) {
		this.astPartAsm = astPartAsm;
	}

	public String getTestStation() {
		return this.testStation;
	}

	public void setTestStation(String testStation) {
		this.testStation = testStation;
	}

	public String getTesterName() {
		return this.testerName;
	}

	public void setTesterName(String testerName) {
		this.testerName = testerName;
	}

	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getTestSystemNm() {
		return this.testSystemNm;
	}

	public void setTestSystemNm(String testSystemNm) {
		this.testSystemNm = testSystemNm;
	}

	public Set getAstTestResultItems() {
		return this.astTestResultItems;
	}

	public void setAstTestResultItems(Set astTestResultItems) {
		this.astTestResultItems = astTestResultItems;
	}

}
