package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AstPartAsmAttr generated by hbm2java
 */
public class MinAstPartAsmAttr implements java.io.Serializable {

	private BigDecimal partAsmAttrId;
	private MinAstPartAttr astPartAttr;
	private String valueTx;


	public MinAstPartAsmAttr() {
	}

	public MinAstPartAsmAttr(BigDecimal partAsmAttrId, MinAstPartAttr astPartAttr) {
		this.partAsmAttrId = partAsmAttrId;
		this.astPartAttr = astPartAttr;
	}

	public MinAstPartAsmAttr(BigDecimal partAsmAttrId,
			MinAstPartAttr astPartAttr, String valueTx ) {
		this.partAsmAttrId = partAsmAttrId;
		this.astPartAttr = astPartAttr;
		this.valueTx = valueTx;
	}

	public BigDecimal getPartAsmAttrId() {
		return this.partAsmAttrId;
	}

	public void setPartAsmAttrId(BigDecimal partAsmAttrId) {
		this.partAsmAttrId = partAsmAttrId;
	}


	public MinAstPartAttr getAstPartAttr() {
		return this.astPartAttr;
	}

	public void setAstPartAttr(MinAstPartAttr astPartAttr) {
		this.astPartAttr = astPartAttr;
	}

	public String getValueTx() {
		return this.valueTx;
	}

	public void setValueTx(String valueTx) {
		this.valueTx = valueTx;
	}


}
