package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstPartAsm generated by hbm2java
 */
public class MinAstPartAsm implements java.io.Serializable {

	private BigDecimal partAsmId;
	private MinAstPart astPart;
	private Set astTestResults = new HashSet(0);
	private Set astPartAsmAttrs = new HashSet(0);
	private Set astTestResultItems = new HashSet(0);
	private Set astPartAsms = new HashSet(0);

	public MinAstPartAsm() {
	}

	public MinAstPartAsm(BigDecimal partAsmId, MinAstPart astPart) {
		this.partAsmId = partAsmId;
		this.astPart = astPart;
	}

	public MinAstPartAsm(BigDecimal partAsmId,
			MinAstPart astPart, Set astTestResults, Set astPartAsmAttrs, Set astTestResultItems, Set astPartAsms) {
		this.partAsmId = partAsmId;
		this.astPart = astPart;
		this.astPartAsmAttrs = astPartAsmAttrs;
		this.astTestResultItems = astTestResultItems;
		this.astPartAsms = astPartAsms;
		this.astTestResults = astTestResults;
	}

	public BigDecimal getPartAsmId() {
		return this.partAsmId;
	}

	public void setPartAsmId(BigDecimal partAsmId) {
		this.partAsmId = partAsmId;
	}

	

	public MinAstPart getAstPart() {
		return this.astPart;
	}

	public void setAstPart(MinAstPart astPart) {
		this.astPart = astPart;
	}


	public Set getAstPartAsmAttrs() {
		return this.astPartAsmAttrs;
	}

	public void setAstPartAsmAttrs(Set astPartAsmAttrs) {
		this.astPartAsmAttrs = astPartAsmAttrs;
	}

	public Set getAstTestResultItems() {
		return this.astTestResultItems;
	}

	public void setAstTestResultItems(Set astTestResultItems) {
		this.astTestResultItems = astTestResultItems;
	}
	
	public Set getAstPartAsms() {
		return this.astPartAsms;
	}

	public void setAstPartAsms(Set astPartAsms) {
		this.astPartAsms = astPartAsms;
	}
	
	public Set getAstTestResults() {
		return this.astTestResults;
	}

	public void setAstTestResults(Set astTestResults) {
		this.astTestResults = astTestResults;
	}

}
