package com.avnet.alapps.model.alapps;

// Generated Apr 20, 2016 1:55:16 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AstPart generated by hbm2java
 */
public class MinAstPart implements java.io.Serializable {

	private BigDecimal partId;
	private MinAstCompType astCompType;
	private String activeFl;
	private String keyValue;
	private Set astPartAttrs = new HashSet(0);


	public MinAstPart() {
	}

	public MinAstPart(BigDecimal partId, MinAstCompType astCompType, String activeFl,
			String keyValue) {
		this.partId = partId;
		this.astCompType = astCompType;
		this.activeFl = activeFl;
		this.keyValue = keyValue;
	}

	public MinAstPart(BigDecimal partId, MinAstCompType astCompType, String activeFl,
			String keyValue, Set astPartAttrs) {
		this.partId = partId;
		this.astCompType = astCompType;
		this.activeFl = activeFl;
		this.keyValue = keyValue;
		this.astPartAttrs = astPartAttrs;
	}

	public BigDecimal getPartId() {
		return this.partId;
	}

	public void setPartId(BigDecimal partId) {
		this.partId = partId;
	}

	public MinAstCompType getAstCompType() {
		return this.astCompType;
	}

	public void setAstCompType(MinAstCompType astCompType) {
		this.astCompType = astCompType;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}


	public Set getAstPartAttrs() {
		return this.astPartAttrs;
	}

	public void setAstPartAttrs(Set astPartAttrs) {
		this.astPartAttrs = astPartAttrs;
	}


}
