package com.avnet.alapps.model.alapps;

// Generated Dec 8, 2015 6:04:26 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AstTestResultItem generated by hbm2java
 */
public class MinAstTestResultItem implements java.io.Serializable {

	private BigDecimal testResultItemId;
	private MinAstTestResult astTestResult;
	private AstTestResultCode astTestResultCode;
	private String resultCodeNm;
	private String resultCodeDs;
	private String testNm;
	private String testDs;
	private Date createDt;
	private String extractedVal;

	public MinAstTestResultItem() {
	}

	public MinAstTestResultItem(BigDecimal testResultItemId, Date createDt) {
		this.testResultItemId = testResultItemId;
		this.createDt = createDt;
	}

	public MinAstTestResultItem(BigDecimal testResultItemId, MinAstTestResult astTestResult, AstTestResultCode astTestResultCode,
			 String resultCodeNm, String resultCodeDs,
			String testNm, String testDs, Date createDt, String extractedVal) {
		this.testResultItemId = testResultItemId;
		this.astTestResult = astTestResult;
		this.astTestResultCode = astTestResultCode;
	
		this.resultCodeNm = resultCodeNm;
		this.resultCodeDs = resultCodeDs;
		this.testNm = testNm;
		this.testDs = testDs;
		this.createDt = createDt;
		this.extractedVal = extractedVal;
	}

	public BigDecimal getTestResultItemId() {
		return this.testResultItemId;
	}

	public void setTestResultItemId(BigDecimal testResultItemId) {
		this.testResultItemId = testResultItemId;
	}


	public AstTestResultCode getAstTestResultCode() {
		return this.astTestResultCode;
	}

	public void setAstTestResultCode(AstTestResultCode astTestResultCode) {
		this.astTestResultCode = astTestResultCode;
	}

	public String getResultCodeNm() {
		return this.resultCodeNm;
	}

	public void setResultCodeNm(String resultCodeNm) {
		this.resultCodeNm = resultCodeNm;
	}

	public String getResultCodeDs() {
		return this.resultCodeDs;
	}

	public void setResultCodeDs(String resultCodeDs) {
		this.resultCodeDs = resultCodeDs;
	}

	public String getTestNm() {
		return this.testNm;
	}

	public void setTestNm(String testNm) {
		this.testNm = testNm;
	}

	public String getTestDs() {
		return this.testDs;
	}

	public void setTestDs(String testDs) {
		this.testDs = testDs;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getExtractedVal() {
		return this.extractedVal;
	}

	public void setExtractedVal(String extractedVal) {
		this.extractedVal = extractedVal;
	}
	
	public MinAstTestResult getAstTestResult() {
		return this.astTestResult;
	}

	public void setAstTestResult(MinAstTestResult astTestResult) {
		this.astTestResult = astTestResult;
	}

}
