package com.avnet.alapps.model.dbconnect;

// Generated Feb 2, 2016 5:45:54 PM by Hibernate Tools 4.3.1

/**
 * CarrierCode generated by hbm2java
 */
public class CarrierCode implements java.io.Serializable {

	private String carrierCode;
	private String carrierName;

	public CarrierCode() {
	}

	public CarrierCode(String carrierCode) {
		this.carrierCode = carrierCode;
	}

	public CarrierCode(String carrierCode, String carrierName) {
		this.carrierCode = carrierCode;
		this.carrierName = carrierName;
	}

	public String getCarrierCode() {
		return this.carrierCode;
	}

	public void setCarrierCode(String carrierCode) {
		this.carrierCode = carrierCode;
	}

	public String getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

}
