package com.avnet.alapps.model.dbconnect;

// Generated Jan 4, 2016 4:31:43 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DataCaptureCharacteristic generated by hbm2java
 */
public class DataCaptureCharacteristic implements java.io.Serializable {

	private BigDecimal dataCaptureCharacteristicId;
	private String characteristicCd;
	private String characteristicNm;
	private BigDecimal sourceErpId;
	private String activeFl;
	private Date applCreateDt;
	private Date applUpdateDt;
	private String applCreateUserId;
	private String applUpdateUserId;
	private BigDecimal dataCaptureCharCatgId;
	private Set dataCaptureRequirements = new HashSet(0);

	public DataCaptureCharacteristic() {
	}

	public DataCaptureCharacteristic(BigDecimal dataCaptureCharacteristicId,
			String characteristicCd, String characteristicNm,
			BigDecimal sourceErpId, String activeFl, Date applCreateDt,
			String applCreateUserId, BigDecimal dataCaptureCharCatgId) {
		this.dataCaptureCharacteristicId = dataCaptureCharacteristicId;
		this.characteristicCd = characteristicCd;
		this.characteristicNm = characteristicNm;
		this.sourceErpId = sourceErpId;
		this.activeFl = activeFl;
		this.applCreateDt = applCreateDt;
		this.applCreateUserId = applCreateUserId;
		this.dataCaptureCharCatgId = dataCaptureCharCatgId;
	}

	public DataCaptureCharacteristic(BigDecimal dataCaptureCharacteristicId,
			String characteristicCd, String characteristicNm,
			BigDecimal sourceErpId, String activeFl, Date applCreateDt,
			Date applUpdateDt, String applCreateUserId,
			String applUpdateUserId, BigDecimal dataCaptureCharCatgId,
			Set dataCaptureRequirements) {
		this.dataCaptureCharacteristicId = dataCaptureCharacteristicId;
		this.characteristicCd = characteristicCd;
		this.characteristicNm = characteristicNm;
		this.sourceErpId = sourceErpId;
		this.activeFl = activeFl;
		this.applCreateDt = applCreateDt;
		this.applUpdateDt = applUpdateDt;
		this.applCreateUserId = applCreateUserId;
		this.applUpdateUserId = applUpdateUserId;
		this.dataCaptureCharCatgId = dataCaptureCharCatgId;
		this.dataCaptureRequirements = dataCaptureRequirements;
	}

	public BigDecimal getDataCaptureCharacteristicId() {
		return this.dataCaptureCharacteristicId;
	}

	public void setDataCaptureCharacteristicId(
			BigDecimal dataCaptureCharacteristicId) {
		this.dataCaptureCharacteristicId = dataCaptureCharacteristicId;
	}

	public String getCharacteristicCd() {
		return this.characteristicCd;
	}

	public void setCharacteristicCd(String characteristicCd) {
		this.characteristicCd = characteristicCd;
	}

	public String getCharacteristicNm() {
		return this.characteristicNm;
	}

	public void setCharacteristicNm(String characteristicNm) {
		this.characteristicNm = characteristicNm;
	}

	public BigDecimal getSourceErpId() {
		return this.sourceErpId;
	}

	public void setSourceErpId(BigDecimal sourceErpId) {
		this.sourceErpId = sourceErpId;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public Date getApplCreateDt() {
		return this.applCreateDt;
	}

	public void setApplCreateDt(Date applCreateDt) {
		this.applCreateDt = applCreateDt;
	}

	public Date getApplUpdateDt() {
		return this.applUpdateDt;
	}

	public void setApplUpdateDt(Date applUpdateDt) {
		this.applUpdateDt = applUpdateDt;
	}

	public String getApplCreateUserId() {
		return this.applCreateUserId;
	}

	public void setApplCreateUserId(String applCreateUserId) {
		this.applCreateUserId = applCreateUserId;
	}

	public String getApplUpdateUserId() {
		return this.applUpdateUserId;
	}

	public void setApplUpdateUserId(String applUpdateUserId) {
		this.applUpdateUserId = applUpdateUserId;
	}

	public BigDecimal getDataCaptureCharCatgId() {
		return this.dataCaptureCharCatgId;
	}

	public void setDataCaptureCharCatgId(BigDecimal dataCaptureCharCatgId) {
		this.dataCaptureCharCatgId = dataCaptureCharCatgId;
	}

	public Set getDataCaptureRequirements() {
		return this.dataCaptureRequirements;
	}

	public void setDataCaptureRequirements(Set dataCaptureRequirements) {
		this.dataCaptureRequirements = dataCaptureRequirements;
	}

}
