package com.avnet.alapps.model.dbconnect;

// Generated Jan 4, 2016 4:31:43 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DataCaptureRequirement generated by hbm2java
 */
public class DataCaptureRequirement implements java.io.Serializable {

	private BigDecimal dataCaptureRequirementId;
	private DataCaptureCharacteristic dataCaptureCharacteristic;
	private String partOnlyFl;
	private BigDecimal requirementQt;
	private String requirementDs;
	private String activeFl;
	private Date applCreateDt;
	private Date applUpdateDt;
	private String applCreateUserId;
	private String applUpdateUserId;
	private Set dataCaptureDetails = new HashSet(0);

	public DataCaptureRequirement() {
	}

	public DataCaptureRequirement(BigDecimal dataCaptureRequirementId,
			DataCaptureCharacteristic dataCaptureCharacteristic,
			String partOnlyFl, BigDecimal requirementQt, String requirementDs,
			String activeFl, Date applCreateDt, String applCreateUserId) {
		this.dataCaptureRequirementId = dataCaptureRequirementId;
		this.dataCaptureCharacteristic = dataCaptureCharacteristic;
		this.partOnlyFl = partOnlyFl;
		this.requirementQt = requirementQt;
		this.requirementDs = requirementDs;
		this.activeFl = activeFl;
		this.applCreateDt = applCreateDt;
		this.applCreateUserId = applCreateUserId;
	}

	public DataCaptureRequirement(BigDecimal dataCaptureRequirementId,
			DataCaptureCharacteristic dataCaptureCharacteristic,
			String partOnlyFl, BigDecimal requirementQt, String requirementDs,
			String activeFl, Date applCreateDt, Date applUpdateDt,
			String applCreateUserId, String applUpdateUserId,
			Set dataCaptureDetails) {
		this.dataCaptureRequirementId = dataCaptureRequirementId;
		this.dataCaptureCharacteristic = dataCaptureCharacteristic;
		this.partOnlyFl = partOnlyFl;
		this.requirementQt = requirementQt;
		this.requirementDs = requirementDs;
		this.activeFl = activeFl;
		this.applCreateDt = applCreateDt;
		this.applUpdateDt = applUpdateDt;
		this.applCreateUserId = applCreateUserId;
		this.applUpdateUserId = applUpdateUserId;
		this.dataCaptureDetails = dataCaptureDetails;
	}

	public BigDecimal getDataCaptureRequirementId() {
		return this.dataCaptureRequirementId;
	}

	public void setDataCaptureRequirementId(BigDecimal dataCaptureRequirementId) {
		this.dataCaptureRequirementId = dataCaptureRequirementId;
	}

	public DataCaptureCharacteristic getDataCaptureCharacteristic() {
		return this.dataCaptureCharacteristic;
	}

	public void setDataCaptureCharacteristic(
			DataCaptureCharacteristic dataCaptureCharacteristic) {
		this.dataCaptureCharacteristic = dataCaptureCharacteristic;
	}

	public String getPartOnlyFl() {
		return this.partOnlyFl;
	}

	public void setPartOnlyFl(String partOnlyFl) {
		this.partOnlyFl = partOnlyFl;
	}

	public BigDecimal getRequirementQt() {
		return this.requirementQt;
	}

	public void setRequirementQt(BigDecimal requirementQt) {
		this.requirementQt = requirementQt;
	}

	public String getRequirementDs() {
		return this.requirementDs;
	}

	public void setRequirementDs(String requirementDs) {
		this.requirementDs = requirementDs;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public Date getApplCreateDt() {
		return this.applCreateDt;
	}

	public void setApplCreateDt(Date applCreateDt) {
		this.applCreateDt = applCreateDt;
	}

	public Date getApplUpdateDt() {
		return this.applUpdateDt;
	}

	public void setApplUpdateDt(Date applUpdateDt) {
		this.applUpdateDt = applUpdateDt;
	}

	public String getApplCreateUserId() {
		return this.applCreateUserId;
	}

	public void setApplCreateUserId(String applCreateUserId) {
		this.applCreateUserId = applCreateUserId;
	}

	public String getApplUpdateUserId() {
		return this.applUpdateUserId;
	}

	public void setApplUpdateUserId(String applUpdateUserId) {
		this.applUpdateUserId = applUpdateUserId;
	}

	public Set getDataCaptureDetails() {
		return this.dataCaptureDetails;
	}

	public void setDataCaptureDetails(Set dataCaptureDetails) {
		this.dataCaptureDetails = dataCaptureDetails;
	}

}
