package com.avnet.alapps.model.dbconnect;

// Generated Feb 1, 2016 4:06:03 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItsTeam generated by hbm2java
 */
public class ItsTeam implements java.io.Serializable {

	private int itsTeamId;
	private String itsTeamDesc;
	private String activeFl;
	private Date insertDate;
	private String insertUser;
	private Date updateDate;
	private String updateUser;
	private Short targetDefaultFte;
	private Integer targetDollarsPerFte;
	private BigDecimal buildFacilityId;
	private Set projects = new HashSet(0);

	public ItsTeam() {
	}

	public ItsTeam(int itsTeamId, String activeFl, String insertUser) {
		this.itsTeamId = itsTeamId;
		this.activeFl = activeFl;
		this.insertUser = insertUser;
	}

	public ItsTeam(int itsTeamId, String itsTeamDesc, String activeFl,
			Date insertDate, String insertUser, Date updateDate,
			String updateUser, Short targetDefaultFte,
			Integer targetDollarsPerFte, BigDecimal buildFacilityId,
			Set projects) {
		this.itsTeamId = itsTeamId;
		this.itsTeamDesc = itsTeamDesc;
		this.activeFl = activeFl;
		this.insertDate = insertDate;
		this.insertUser = insertUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.targetDefaultFte = targetDefaultFte;
		this.targetDollarsPerFte = targetDollarsPerFte;
		this.buildFacilityId = buildFacilityId;
		this.projects = projects;
	}

	public int getItsTeamId() {
		return this.itsTeamId;
	}

	public void setItsTeamId(int itsTeamId) {
		this.itsTeamId = itsTeamId;
	}

	public String getItsTeamDesc() {
		return this.itsTeamDesc;
	}

	public void setItsTeamDesc(String itsTeamDesc) {
		this.itsTeamDesc = itsTeamDesc;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Short getTargetDefaultFte() {
		return this.targetDefaultFte;
	}

	public void setTargetDefaultFte(Short targetDefaultFte) {
		this.targetDefaultFte = targetDefaultFte;
	}

	public Integer getTargetDollarsPerFte() {
		return this.targetDollarsPerFte;
	}

	public void setTargetDollarsPerFte(Integer targetDollarsPerFte) {
		this.targetDollarsPerFte = targetDollarsPerFte;
	}

	public BigDecimal getBuildFacilityId() {
		return this.buildFacilityId;
	}

	public void setBuildFacilityId(BigDecimal buildFacilityId) {
		this.buildFacilityId = buildFacilityId;
	}

	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

}
