package com.avnet.alapps.model.dbconnect;

// Generated Feb 9, 2016 3:01:04 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Orderheader generated by hbm2java
 */
public class Orderheader implements java.io.Serializable {

	private String scn;
	private String custno;
	private String custpono;
	private String orderstatus;
	private String custponoreleaseno;
	private String specialinstruction;
	private String internalinstruction;
	private String primaryshipcarrier;
	private String balanceshipcarrier;
	private String govtcontractno;
	private String cancelcode;
	private Date lastupdatedate;
	private String note;
	private Date closedate;
	private String buyerphoneno;
	private String custspecdesc;
	private String custdrawdescBom;
	private String isr;
	private String paymentmethod;
	private String govtpriorityrating;
	private Character freightchargecode;
	private String paymenttermscode;
	private String fob;
	private Date bookdate;
	private Character taxableflag;
	private Character creditcategorycode;
	private Character shipcompletecode;
	private Character designwintypecode;
	private String authorizer;
	private Character paytermauthcode;
	private String paytermauthorizer;
	private String tradeterms;
	private Character tradetermauthcode;
	private String tradetermauthorizer;
	private Character shipcarrierflag;
	private Character hotshipflag;
	private String custcarrieracctno;
	private BigDecimal lineitemcount;
	private BigDecimal ordervalue;
	private String webuserid;
	private Date insertdate;
	private String insertuser;
	private Date updatedate;
	private String updateuser;
	private String district;
	private String accountno;
	private String shipplate;
	private String jobno;
	private String b2bindicator;
	private String weborder;
	private String applSorRecordFl;
	private Date applCreateDt;
	private Date applUpdateDt;
	private BigDecimal auditLogKey;
	private String webemailaddress;
	private String buyerName;

	public Orderheader() {
	}

	public Orderheader(String scn, String applSorRecordFl, Date applCreateDt) {
		this.scn = scn;
		this.applSorRecordFl = applSorRecordFl;
		this.applCreateDt = applCreateDt;
	}

	public Orderheader(String scn, String custno, String custpono,
			String orderstatus, String custponoreleaseno,
			String specialinstruction, String internalinstruction,
			String primaryshipcarrier, String balanceshipcarrier,
			String govtcontractno, String cancelcode, Date lastupdatedate,
			String note, Date closedate, String buyerphoneno,
			String custspecdesc, String custdrawdescBom, String isr,
			String paymentmethod, String govtpriorityrating,
			Character freightchargecode, String paymenttermscode, String fob,
			Date bookdate, Character taxableflag, Character creditcategorycode,
			Character shipcompletecode, Character designwintypecode,
			String authorizer, Character paytermauthcode,
			String paytermauthorizer, String tradeterms,
			Character tradetermauthcode, String tradetermauthorizer,
			Character shipcarrierflag, Character hotshipflag,
			String custcarrieracctno, BigDecimal lineitemcount,
			BigDecimal ordervalue, String webuserid, Date insertdate,
			String insertuser, Date updatedate, String updateuser,
			String district, String accountno, String shipplate, String jobno,
			String b2bindicator, String weborder, String applSorRecordFl,
			Date applCreateDt, Date applUpdateDt, BigDecimal auditLogKey,
			String webemailaddress, String buyerName) {
		this.scn = scn;
		this.custno = custno;
		this.custpono = custpono;
		this.orderstatus = orderstatus;
		this.custponoreleaseno = custponoreleaseno;
		this.specialinstruction = specialinstruction;
		this.internalinstruction = internalinstruction;
		this.primaryshipcarrier = primaryshipcarrier;
		this.balanceshipcarrier = balanceshipcarrier;
		this.govtcontractno = govtcontractno;
		this.cancelcode = cancelcode;
		this.lastupdatedate = lastupdatedate;
		this.note = note;
		this.closedate = closedate;
		this.buyerphoneno = buyerphoneno;
		this.custspecdesc = custspecdesc;
		this.custdrawdescBom = custdrawdescBom;
		this.isr = isr;
		this.paymentmethod = paymentmethod;
		this.govtpriorityrating = govtpriorityrating;
		this.freightchargecode = freightchargecode;
		this.paymenttermscode = paymenttermscode;
		this.fob = fob;
		this.bookdate = bookdate;
		this.taxableflag = taxableflag;
		this.creditcategorycode = creditcategorycode;
		this.shipcompletecode = shipcompletecode;
		this.designwintypecode = designwintypecode;
		this.authorizer = authorizer;
		this.paytermauthcode = paytermauthcode;
		this.paytermauthorizer = paytermauthorizer;
		this.tradeterms = tradeterms;
		this.tradetermauthcode = tradetermauthcode;
		this.tradetermauthorizer = tradetermauthorizer;
		this.shipcarrierflag = shipcarrierflag;
		this.hotshipflag = hotshipflag;
		this.custcarrieracctno = custcarrieracctno;
		this.lineitemcount = lineitemcount;
		this.ordervalue = ordervalue;
		this.webuserid = webuserid;
		this.insertdate = insertdate;
		this.insertuser = insertuser;
		this.updatedate = updatedate;
		this.updateuser = updateuser;
		this.district = district;
		this.accountno = accountno;
		this.shipplate = shipplate;
		this.jobno = jobno;
		this.b2bindicator = b2bindicator;
		this.weborder = weborder;
		this.applSorRecordFl = applSorRecordFl;
		this.applCreateDt = applCreateDt;
		this.applUpdateDt = applUpdateDt;
		this.auditLogKey = auditLogKey;
		this.webemailaddress = webemailaddress;
		this.buyerName = buyerName;
	}

	public String getScn() {
		return this.scn;
	}

	public void setScn(String scn) {
		this.scn = scn;
	}

	public String getCustno() {
		return this.custno;
	}

	public void setCustno(String custno) {
		this.custno = custno;
	}

	public String getCustpono() {
		return this.custpono;
	}

	public void setCustpono(String custpono) {
		this.custpono = custpono;
	}

	public String getOrderstatus() {
		return this.orderstatus;
	}

	public void setOrderstatus(String orderstatus) {
		this.orderstatus = orderstatus;
	}

	public String getCustponoreleaseno() {
		return this.custponoreleaseno;
	}

	public void setCustponoreleaseno(String custponoreleaseno) {
		this.custponoreleaseno = custponoreleaseno;
	}

	public String getSpecialinstruction() {
		return this.specialinstruction;
	}

	public void setSpecialinstruction(String specialinstruction) {
		this.specialinstruction = specialinstruction;
	}

	public String getInternalinstruction() {
		return this.internalinstruction;
	}

	public void setInternalinstruction(String internalinstruction) {
		this.internalinstruction = internalinstruction;
	}

	public String getPrimaryshipcarrier() {
		return this.primaryshipcarrier;
	}

	public void setPrimaryshipcarrier(String primaryshipcarrier) {
		this.primaryshipcarrier = primaryshipcarrier;
	}

	public String getBalanceshipcarrier() {
		return this.balanceshipcarrier;
	}

	public void setBalanceshipcarrier(String balanceshipcarrier) {
		this.balanceshipcarrier = balanceshipcarrier;
	}

	public String getGovtcontractno() {
		return this.govtcontractno;
	}

	public void setGovtcontractno(String govtcontractno) {
		this.govtcontractno = govtcontractno;
	}

	public String getCancelcode() {
		return this.cancelcode;
	}

	public void setCancelcode(String cancelcode) {
		this.cancelcode = cancelcode;
	}

	public Date getLastupdatedate() {
		return this.lastupdatedate;
	}

	public void setLastupdatedate(Date lastupdatedate) {
		this.lastupdatedate = lastupdatedate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getClosedate() {
		return this.closedate;
	}

	public void setClosedate(Date closedate) {
		this.closedate = closedate;
	}

	public String getBuyerphoneno() {
		return this.buyerphoneno;
	}

	public void setBuyerphoneno(String buyerphoneno) {
		this.buyerphoneno = buyerphoneno;
	}

	public String getCustspecdesc() {
		return this.custspecdesc;
	}

	public void setCustspecdesc(String custspecdesc) {
		this.custspecdesc = custspecdesc;
	}

	public String getCustdrawdescBom() {
		return this.custdrawdescBom;
	}

	public void setCustdrawdescBom(String custdrawdescBom) {
		this.custdrawdescBom = custdrawdescBom;
	}

	public String getIsr() {
		return this.isr;
	}

	public void setIsr(String isr) {
		this.isr = isr;
	}

	public String getPaymentmethod() {
		return this.paymentmethod;
	}

	public void setPaymentmethod(String paymentmethod) {
		this.paymentmethod = paymentmethod;
	}

	public String getGovtpriorityrating() {
		return this.govtpriorityrating;
	}

	public void setGovtpriorityrating(String govtpriorityrating) {
		this.govtpriorityrating = govtpriorityrating;
	}

	public Character getFreightchargecode() {
		return this.freightchargecode;
	}

	public void setFreightchargecode(Character freightchargecode) {
		this.freightchargecode = freightchargecode;
	}

	public String getPaymenttermscode() {
		return this.paymenttermscode;
	}

	public void setPaymenttermscode(String paymenttermscode) {
		this.paymenttermscode = paymenttermscode;
	}

	public String getFob() {
		return this.fob;
	}

	public void setFob(String fob) {
		this.fob = fob;
	}

	public Date getBookdate() {
		return this.bookdate;
	}

	public void setBookdate(Date bookdate) {
		this.bookdate = bookdate;
	}

	public Character getTaxableflag() {
		return this.taxableflag;
	}

	public void setTaxableflag(Character taxableflag) {
		this.taxableflag = taxableflag;
	}

	public Character getCreditcategorycode() {
		return this.creditcategorycode;
	}

	public void setCreditcategorycode(Character creditcategorycode) {
		this.creditcategorycode = creditcategorycode;
	}

	public Character getShipcompletecode() {
		return this.shipcompletecode;
	}

	public void setShipcompletecode(Character shipcompletecode) {
		this.shipcompletecode = shipcompletecode;
	}

	public Character getDesignwintypecode() {
		return this.designwintypecode;
	}

	public void setDesignwintypecode(Character designwintypecode) {
		this.designwintypecode = designwintypecode;
	}

	public String getAuthorizer() {
		return this.authorizer;
	}

	public void setAuthorizer(String authorizer) {
		this.authorizer = authorizer;
	}

	public Character getPaytermauthcode() {
		return this.paytermauthcode;
	}

	public void setPaytermauthcode(Character paytermauthcode) {
		this.paytermauthcode = paytermauthcode;
	}

	public String getPaytermauthorizer() {
		return this.paytermauthorizer;
	}

	public void setPaytermauthorizer(String paytermauthorizer) {
		this.paytermauthorizer = paytermauthorizer;
	}

	public String getTradeterms() {
		return this.tradeterms;
	}

	public void setTradeterms(String tradeterms) {
		this.tradeterms = tradeterms;
	}

	public Character getTradetermauthcode() {
		return this.tradetermauthcode;
	}

	public void setTradetermauthcode(Character tradetermauthcode) {
		this.tradetermauthcode = tradetermauthcode;
	}

	public String getTradetermauthorizer() {
		return this.tradetermauthorizer;
	}

	public void setTradetermauthorizer(String tradetermauthorizer) {
		this.tradetermauthorizer = tradetermauthorizer;
	}

	public Character getShipcarrierflag() {
		return this.shipcarrierflag;
	}

	public void setShipcarrierflag(Character shipcarrierflag) {
		this.shipcarrierflag = shipcarrierflag;
	}

	public Character getHotshipflag() {
		return this.hotshipflag;
	}

	public void setHotshipflag(Character hotshipflag) {
		this.hotshipflag = hotshipflag;
	}

	public String getCustcarrieracctno() {
		return this.custcarrieracctno;
	}

	public void setCustcarrieracctno(String custcarrieracctno) {
		this.custcarrieracctno = custcarrieracctno;
	}

	public BigDecimal getLineitemcount() {
		return this.lineitemcount;
	}

	public void setLineitemcount(BigDecimal lineitemcount) {
		this.lineitemcount = lineitemcount;
	}

	public BigDecimal getOrdervalue() {
		return this.ordervalue;
	}

	public void setOrdervalue(BigDecimal ordervalue) {
		this.ordervalue = ordervalue;
	}

	public String getWebuserid() {
		return this.webuserid;
	}

	public void setWebuserid(String webuserid) {
		this.webuserid = webuserid;
	}

	public Date getInsertdate() {
		return this.insertdate;
	}

	public void setInsertdate(Date insertdate) {
		this.insertdate = insertdate;
	}

	public String getInsertuser() {
		return this.insertuser;
	}

	public void setInsertuser(String insertuser) {
		this.insertuser = insertuser;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	public String getShipplate() {
		return this.shipplate;
	}

	public void setShipplate(String shipplate) {
		this.shipplate = shipplate;
	}

	public String getJobno() {
		return this.jobno;
	}

	public void setJobno(String jobno) {
		this.jobno = jobno;
	}

	public String getB2bindicator() {
		return this.b2bindicator;
	}

	public void setB2bindicator(String b2bindicator) {
		this.b2bindicator = b2bindicator;
	}

	public String getWeborder() {
		return this.weborder;
	}

	public void setWeborder(String weborder) {
		this.weborder = weborder;
	}

	public String getApplSorRecordFl() {
		return this.applSorRecordFl;
	}

	public void setApplSorRecordFl(String applSorRecordFl) {
		this.applSorRecordFl = applSorRecordFl;
	}

	public Date getApplCreateDt() {
		return this.applCreateDt;
	}

	public void setApplCreateDt(Date applCreateDt) {
		this.applCreateDt = applCreateDt;
	}

	public Date getApplUpdateDt() {
		return this.applUpdateDt;
	}

	public void setApplUpdateDt(Date applUpdateDt) {
		this.applUpdateDt = applUpdateDt;
	}

	public BigDecimal getAuditLogKey() {
		return this.auditLogKey;
	}

	public void setAuditLogKey(BigDecimal auditLogKey) {
		this.auditLogKey = auditLogKey;
	}

	public String getWebemailaddress() {
		return this.webemailaddress;
	}

	public void setWebemailaddress(String webemailaddress) {
		this.webemailaddress = webemailaddress;
	}

	public String getBuyerName() {
		return this.buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

}
