package com.avnet.alapps.model.dbconnect;

// Generated Mar 23, 2016 12:12:00 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Orderaddress generated by hbm2java
 */
public class Orderaddress implements java.io.Serializable {

	private String scn;
	private String billtoname;
	private String billtoaddress1;
	private String billtoaddress2;
	private String billtoaddress3;
	private String billtocity;
	private String billtostateprovince;
	private String billtopostalcode;
	private String billtocountry;
	private String billtoattention;
	private String shiptoname;
	private String shiptoaddress1;
	private String shiptoaddress2;
	private String shiptoaddress3;
	private String shiptocity;
	private String shiptostateprovince;
	private String shiptopostalcode;
	private String shiptocountry;
	private String shiptoattention;
	private String lastupdatedate;
	private String lastupdatetime;
	private BigDecimal genesiscreatedate;
	private BigDecimal genesiscreatetime;
	private Date insertdate;
	private String insertuser;
	private Date updatedate;
	private String updateuser;
	private String applSorRecordFl;
	private Date applCreateDt;
	private Date applUpdateDt;

	public Orderaddress() {
	}

	public Orderaddress(String scn, String applSorRecordFl, Date applCreateDt) {
		this.scn = scn;
		this.applSorRecordFl = applSorRecordFl;
		this.applCreateDt = applCreateDt;
	}

	public Orderaddress(String scn, String billtoname, String billtoaddress1,
			String billtoaddress2, String billtoaddress3, String billtocity,
			String billtostateprovince, String billtopostalcode,
			String billtocountry, String billtoattention, String shiptoname,
			String shiptoaddress1, String shiptoaddress2,
			String shiptoaddress3, String shiptocity,
			String shiptostateprovince, String shiptopostalcode,
			String shiptocountry, String shiptoattention,
			String lastupdatedate, String lastupdatetime,
			BigDecimal genesiscreatedate, BigDecimal genesiscreatetime,
			Date insertdate, String insertuser, Date updatedate,
			String updateuser, String applSorRecordFl, Date applCreateDt,
			Date applUpdateDt) {
		this.scn = scn;
		this.billtoname = billtoname;
		this.billtoaddress1 = billtoaddress1;
		this.billtoaddress2 = billtoaddress2;
		this.billtoaddress3 = billtoaddress3;
		this.billtocity = billtocity;
		this.billtostateprovince = billtostateprovince;
		this.billtopostalcode = billtopostalcode;
		this.billtocountry = billtocountry;
		this.billtoattention = billtoattention;
		this.shiptoname = shiptoname;
		this.shiptoaddress1 = shiptoaddress1;
		this.shiptoaddress2 = shiptoaddress2;
		this.shiptoaddress3 = shiptoaddress3;
		this.shiptocity = shiptocity;
		this.shiptostateprovince = shiptostateprovince;
		this.shiptopostalcode = shiptopostalcode;
		this.shiptocountry = shiptocountry;
		this.shiptoattention = shiptoattention;
		this.lastupdatedate = lastupdatedate;
		this.lastupdatetime = lastupdatetime;
		this.genesiscreatedate = genesiscreatedate;
		this.genesiscreatetime = genesiscreatetime;
		this.insertdate = insertdate;
		this.insertuser = insertuser;
		this.updatedate = updatedate;
		this.updateuser = updateuser;
		this.applSorRecordFl = applSorRecordFl;
		this.applCreateDt = applCreateDt;
		this.applUpdateDt = applUpdateDt;
	}

	public String getScn() {
		return this.scn;
	}

	public void setScn(String scn) {
		this.scn = scn;
	}

	public String getBilltoname() {
		return this.billtoname;
	}

	public void setBilltoname(String billtoname) {
		this.billtoname = billtoname;
	}

	public String getBilltoaddress1() {
		return this.billtoaddress1;
	}

	public void setBilltoaddress1(String billtoaddress1) {
		this.billtoaddress1 = billtoaddress1;
	}

	public String getBilltoaddress2() {
		return this.billtoaddress2;
	}

	public void setBilltoaddress2(String billtoaddress2) {
		this.billtoaddress2 = billtoaddress2;
	}

	public String getBilltoaddress3() {
		return this.billtoaddress3;
	}

	public void setBilltoaddress3(String billtoaddress3) {
		this.billtoaddress3 = billtoaddress3;
	}

	public String getBilltocity() {
		return this.billtocity;
	}

	public void setBilltocity(String billtocity) {
		this.billtocity = billtocity;
	}

	public String getBilltostateprovince() {
		return this.billtostateprovince;
	}

	public void setBilltostateprovince(String billtostateprovince) {
		this.billtostateprovince = billtostateprovince;
	}

	public String getBilltopostalcode() {
		return this.billtopostalcode;
	}

	public void setBilltopostalcode(String billtopostalcode) {
		this.billtopostalcode = billtopostalcode;
	}

	public String getBilltocountry() {
		return this.billtocountry;
	}

	public void setBilltocountry(String billtocountry) {
		this.billtocountry = billtocountry;
	}

	public String getBilltoattention() {
		return this.billtoattention;
	}

	public void setBilltoattention(String billtoattention) {
		this.billtoattention = billtoattention;
	}

	public String getShiptoname() {
		return this.shiptoname;
	}

	public void setShiptoname(String shiptoname) {
		this.shiptoname = shiptoname;
	}

	public String getShiptoaddress1() {
		return this.shiptoaddress1;
	}

	public void setShiptoaddress1(String shiptoaddress1) {
		this.shiptoaddress1 = shiptoaddress1;
	}

	public String getShiptoaddress2() {
		return this.shiptoaddress2;
	}

	public void setShiptoaddress2(String shiptoaddress2) {
		this.shiptoaddress2 = shiptoaddress2;
	}

	public String getShiptoaddress3() {
		return this.shiptoaddress3;
	}

	public void setShiptoaddress3(String shiptoaddress3) {
		this.shiptoaddress3 = shiptoaddress3;
	}

	public String getShiptocity() {
		return this.shiptocity;
	}

	public void setShiptocity(String shiptocity) {
		this.shiptocity = shiptocity;
	}

	public String getShiptostateprovince() {
		return this.shiptostateprovince;
	}

	public void setShiptostateprovince(String shiptostateprovince) {
		this.shiptostateprovince = shiptostateprovince;
	}

	public String getShiptopostalcode() {
		return this.shiptopostalcode;
	}

	public void setShiptopostalcode(String shiptopostalcode) {
		this.shiptopostalcode = shiptopostalcode;
	}

	public String getShiptocountry() {
		return this.shiptocountry;
	}

	public void setShiptocountry(String shiptocountry) {
		this.shiptocountry = shiptocountry;
	}

	public String getShiptoattention() {
		return this.shiptoattention;
	}

	public void setShiptoattention(String shiptoattention) {
		this.shiptoattention = shiptoattention;
	}

	public String getLastupdatedate() {
		return this.lastupdatedate;
	}

	public void setLastupdatedate(String lastupdatedate) {
		this.lastupdatedate = lastupdatedate;
	}

	public String getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(String lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	public BigDecimal getGenesiscreatedate() {
		return this.genesiscreatedate;
	}

	public void setGenesiscreatedate(BigDecimal genesiscreatedate) {
		this.genesiscreatedate = genesiscreatedate;
	}

	public BigDecimal getGenesiscreatetime() {
		return this.genesiscreatetime;
	}

	public void setGenesiscreatetime(BigDecimal genesiscreatetime) {
		this.genesiscreatetime = genesiscreatetime;
	}

	public Date getInsertdate() {
		return this.insertdate;
	}

	public void setInsertdate(Date insertdate) {
		this.insertdate = insertdate;
	}

	public String getInsertuser() {
		return this.insertuser;
	}

	public void setInsertuser(String insertuser) {
		this.insertuser = insertuser;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	public String getApplSorRecordFl() {
		return this.applSorRecordFl;
	}

	public void setApplSorRecordFl(String applSorRecordFl) {
		this.applSorRecordFl = applSorRecordFl;
	}

	public Date getApplCreateDt() {
		return this.applCreateDt;
	}

	public void setApplCreateDt(Date applCreateDt) {
		this.applCreateDt = applCreateDt;
	}

	public Date getApplUpdateDt() {
		return this.applUpdateDt;
	}

	public void setApplUpdateDt(Date applUpdateDt) {
		this.applUpdateDt = applUpdateDt;
	}

}
