package com.avnet.alapps.model.dbconnect;

// Generated Aug 22, 2016 12:57:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductionOrderHeader generated by hbm2java
 */
public class ProductionOrderHeader implements java.io.Serializable {

	private ProductionOrderHeaderId id;
	private String salesOrderNo;
	private String orderTypeCd;
	private BigDecimal productionOrderQt;
	private Date squareSetDt;
	private String sapMaterialNo;
	private String plantCd;
	private String mfgpartno;
	private Date createDt;
	private String osiRequiredFl;
	private Date applCreateDt;
	private String applCreateUserid;
	private Date applUpdateDt;
	private String applUpdateUserid;
	private Integer salesOrderLineItemNo;
	private String partDescription;
	private String manufacturerNm;
	private String serialNoRequiredFl;
	private String toplevelUom;
	private String batchNo;
	private BigDecimal totalCostAm;
	private BigDecimal totalResaleAm;
	private BigDecimal integrationCostAm;
	private Date materialAvailableDt;
	private Date basicStartDt;
	private Date basicEndDt;
	private String specialInstructions2Tx;
	private Long origProdOrderNo;
	private String splitFl;
	private String plannedOrderNo;
	private String governmentContractNo;
	private String priorityCd;
	private String aogCd;
	private String matrnDs;
	private String collectiveOrderFl;
	private BigDecimal parentProdOrderNo;
	private BigDecimal parentOrderLineItemNo;
	private BigDecimal leadProdOrderNo;
	private BigDecimal childOrderQt;

	public ProductionOrderHeader() {
	}

	public ProductionOrderHeader(ProductionOrderHeaderId id,
			BigDecimal productionOrderQt, String sapMaterialNo, String plantCd,
			Date createDt, Date applCreateDt) {
		this.id = id;
		this.productionOrderQt = productionOrderQt;
		this.sapMaterialNo = sapMaterialNo;
		this.plantCd = plantCd;
		this.createDt = createDt;
		this.applCreateDt = applCreateDt;
	}

	public ProductionOrderHeader(ProductionOrderHeaderId id,
			String salesOrderNo, String orderTypeCd,
			BigDecimal productionOrderQt, Date squareSetDt,
			String sapMaterialNo, String plantCd, String mfgpartno,
			Date createDt, String osiRequiredFl, Date applCreateDt,
			String applCreateUserid, Date applUpdateDt,
			String applUpdateUserid, Integer salesOrderLineItemNo,
			String partDescription, String manufacturerNm,
			String serialNoRequiredFl, String toplevelUom, String batchNo,
			BigDecimal totalCostAm, BigDecimal totalResaleAm,
			BigDecimal integrationCostAm, Date materialAvailableDt,
			Date basicStartDt, Date basicEndDt, String specialInstructions2Tx,
			Long origProdOrderNo, String splitFl, String plannedOrderNo,
			String governmentContractNo, String priorityCd, String aogCd,
			String matrnDs, String collectiveOrderFl,
			BigDecimal parentProdOrderNo, BigDecimal parentOrderLineItemNo,
			BigDecimal leadProdOrderNo, BigDecimal childOrderQt) {
		this.id = id;
		this.salesOrderNo = salesOrderNo;
		this.orderTypeCd = orderTypeCd;
		this.productionOrderQt = productionOrderQt;
		this.squareSetDt = squareSetDt;
		this.sapMaterialNo = sapMaterialNo;
		this.plantCd = plantCd;
		this.mfgpartno = mfgpartno;
		this.createDt = createDt;
		this.osiRequiredFl = osiRequiredFl;
		this.applCreateDt = applCreateDt;
		this.applCreateUserid = applCreateUserid;
		this.applUpdateDt = applUpdateDt;
		this.applUpdateUserid = applUpdateUserid;
		this.salesOrderLineItemNo = salesOrderLineItemNo;
		this.partDescription = partDescription;
		this.manufacturerNm = manufacturerNm;
		this.serialNoRequiredFl = serialNoRequiredFl;
		this.toplevelUom = toplevelUom;
		this.batchNo = batchNo;
		this.totalCostAm = totalCostAm;
		this.totalResaleAm = totalResaleAm;
		this.integrationCostAm = integrationCostAm;
		this.materialAvailableDt = materialAvailableDt;
		this.basicStartDt = basicStartDt;
		this.basicEndDt = basicEndDt;
		this.specialInstructions2Tx = specialInstructions2Tx;
		this.origProdOrderNo = origProdOrderNo;
		this.splitFl = splitFl;
		this.plannedOrderNo = plannedOrderNo;
		this.governmentContractNo = governmentContractNo;
		this.priorityCd = priorityCd;
		this.aogCd = aogCd;
		this.matrnDs = matrnDs;
		this.collectiveOrderFl = collectiveOrderFl;
		this.parentProdOrderNo = parentProdOrderNo;
		this.parentOrderLineItemNo = parentOrderLineItemNo;
		this.leadProdOrderNo = leadProdOrderNo;
		this.childOrderQt = childOrderQt;
	}

	public ProductionOrderHeaderId getId() {
		return this.id;
	}

	public void setId(ProductionOrderHeaderId id) {
		this.id = id;
	}

	public String getSalesOrderNo() {
		return this.salesOrderNo;
	}

	public void setSalesOrderNo(String salesOrderNo) {
		this.salesOrderNo = salesOrderNo;
	}

	public String getOrderTypeCd() {
		return this.orderTypeCd;
	}

	public void setOrderTypeCd(String orderTypeCd) {
		this.orderTypeCd = orderTypeCd;
	}

	public BigDecimal getProductionOrderQt() {
		return this.productionOrderQt;
	}

	public void setProductionOrderQt(BigDecimal productionOrderQt) {
		this.productionOrderQt = productionOrderQt;
	}

	public Date getSquareSetDt() {
		return this.squareSetDt;
	}

	public void setSquareSetDt(Date squareSetDt) {
		this.squareSetDt = squareSetDt;
	}

	public String getSapMaterialNo() {
		return this.sapMaterialNo;
	}

	public void setSapMaterialNo(String sapMaterialNo) {
		this.sapMaterialNo = sapMaterialNo;
	}

	public String getPlantCd() {
		return this.plantCd;
	}

	public void setPlantCd(String plantCd) {
		this.plantCd = plantCd;
	}

	public String getMfgpartno() {
		return this.mfgpartno;
	}

	public void setMfgpartno(String mfgpartno) {
		this.mfgpartno = mfgpartno;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getOsiRequiredFl() {
		return this.osiRequiredFl;
	}

	public void setOsiRequiredFl(String osiRequiredFl) {
		this.osiRequiredFl = osiRequiredFl;
	}

	public Date getApplCreateDt() {
		return this.applCreateDt;
	}

	public void setApplCreateDt(Date applCreateDt) {
		this.applCreateDt = applCreateDt;
	}

	public String getApplCreateUserid() {
		return this.applCreateUserid;
	}

	public void setApplCreateUserid(String applCreateUserid) {
		this.applCreateUserid = applCreateUserid;
	}

	public Date getApplUpdateDt() {
		return this.applUpdateDt;
	}

	public void setApplUpdateDt(Date applUpdateDt) {
		this.applUpdateDt = applUpdateDt;
	}

	public String getApplUpdateUserid() {
		return this.applUpdateUserid;
	}

	public void setApplUpdateUserid(String applUpdateUserid) {
		this.applUpdateUserid = applUpdateUserid;
	}

	public Integer getSalesOrderLineItemNo() {
		return this.salesOrderLineItemNo;
	}

	public void setSalesOrderLineItemNo(Integer salesOrderLineItemNo) {
		this.salesOrderLineItemNo = salesOrderLineItemNo;
	}

	public String getPartDescription() {
		return this.partDescription;
	}

	public void setPartDescription(String partDescription) {
		this.partDescription = partDescription;
	}

	public String getManufacturerNm() {
		return this.manufacturerNm;
	}

	public void setManufacturerNm(String manufacturerNm) {
		this.manufacturerNm = manufacturerNm;
	}

	public String getSerialNoRequiredFl() {
		return this.serialNoRequiredFl;
	}

	public void setSerialNoRequiredFl(String serialNoRequiredFl) {
		this.serialNoRequiredFl = serialNoRequiredFl;
	}

	public String getToplevelUom() {
		return this.toplevelUom;
	}

	public void setToplevelUom(String toplevelUom) {
		this.toplevelUom = toplevelUom;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public BigDecimal getTotalCostAm() {
		return this.totalCostAm;
	}

	public void setTotalCostAm(BigDecimal totalCostAm) {
		this.totalCostAm = totalCostAm;
	}

	public BigDecimal getTotalResaleAm() {
		return this.totalResaleAm;
	}

	public void setTotalResaleAm(BigDecimal totalResaleAm) {
		this.totalResaleAm = totalResaleAm;
	}

	public BigDecimal getIntegrationCostAm() {
		return this.integrationCostAm;
	}

	public void setIntegrationCostAm(BigDecimal integrationCostAm) {
		this.integrationCostAm = integrationCostAm;
	}

	public Date getMaterialAvailableDt() {
		return this.materialAvailableDt;
	}

	public void setMaterialAvailableDt(Date materialAvailableDt) {
		this.materialAvailableDt = materialAvailableDt;
	}

	public Date getBasicStartDt() {
		return this.basicStartDt;
	}

	public void setBasicStartDt(Date basicStartDt) {
		this.basicStartDt = basicStartDt;
	}

	public Date getBasicEndDt() {
		return this.basicEndDt;
	}

	public void setBasicEndDt(Date basicEndDt) {
		this.basicEndDt = basicEndDt;
	}

	public String getSpecialInstructions2Tx() {
		return this.specialInstructions2Tx;
	}

	public void setSpecialInstructions2Tx(String specialInstructions2Tx) {
		this.specialInstructions2Tx = specialInstructions2Tx;
	}

	public Long getOrigProdOrderNo() {
		return this.origProdOrderNo;
	}

	public void setOrigProdOrderNo(Long origProdOrderNo) {
		this.origProdOrderNo = origProdOrderNo;
	}

	public String getSplitFl() {
		return this.splitFl;
	}

	public void setSplitFl(String splitFl) {
		this.splitFl = splitFl;
	}

	public String getPlannedOrderNo() {
		return this.plannedOrderNo;
	}

	public void setPlannedOrderNo(String plannedOrderNo) {
		this.plannedOrderNo = plannedOrderNo;
	}

	public String getGovernmentContractNo() {
		return this.governmentContractNo;
	}

	public void setGovernmentContractNo(String governmentContractNo) {
		this.governmentContractNo = governmentContractNo;
	}

	public String getPriorityCd() {
		return this.priorityCd;
	}

	public void setPriorityCd(String priorityCd) {
		this.priorityCd = priorityCd;
	}

	public String getAogCd() {
		return this.aogCd;
	}

	public void setAogCd(String aogCd) {
		this.aogCd = aogCd;
	}

	public String getMatrnDs() {
		return this.matrnDs;
	}

	public void setMatrnDs(String matrnDs) {
		this.matrnDs = matrnDs;
	}

	public String getCollectiveOrderFl() {
		return this.collectiveOrderFl;
	}

	public void setCollectiveOrderFl(String collectiveOrderFl) {
		this.collectiveOrderFl = collectiveOrderFl;
	}

	public BigDecimal getParentProdOrderNo() {
		return this.parentProdOrderNo;
	}

	public void setParentProdOrderNo(BigDecimal parentProdOrderNo) {
		this.parentProdOrderNo = parentProdOrderNo;
	}

	public BigDecimal getParentOrderLineItemNo() {
		return this.parentOrderLineItemNo;
	}

	public void setParentOrderLineItemNo(BigDecimal parentOrderLineItemNo) {
		this.parentOrderLineItemNo = parentOrderLineItemNo;
	}

	public BigDecimal getLeadProdOrderNo() {
		return this.leadProdOrderNo;
	}

	public void setLeadProdOrderNo(BigDecimal leadProdOrderNo) {
		this.leadProdOrderNo = leadProdOrderNo;
	}

	public BigDecimal getChildOrderQt() {
		return this.childOrderQt;
	}

	public void setChildOrderQt(BigDecimal childOrderQt) {
		this.childOrderQt = childOrderQt;
	}

}
