package com.avnet.alapps.model.dbconnect;

// Generated Jan 4, 2016 4:31:43 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private BigDecimal projectId;
	private String custno;
	private String companyname;
	private String custrevisionno;
	private String projectdesc;
	private String custpartno;
	private Integer productionqty;
	private Integer runrate;
	private BigDecimal margin;
	private BigDecimal systemcost;
	private Character approvalflag;
	private String instructions;
	private String aacRevisionNum;
	private String integrationType;
	private String scope;
	private String amsnumber;
	private String projectName;
	private String activity;
	private String status;
	private Date protoRequiredDate;
	private Date protoMaterialrecdate;
	private Date protoShipdate;
	private Date protoScheddate;
	private String protoLocation;
	private String buildFacilityName;
	private Boolean hardwareOnly;
	private Boolean buildFromParts;
	private Boolean requireImage;
	private Boolean specialLabel;
	private Boolean specialBox;
	private BigDecimal difficultyLevel;
	private String clientNotes;
	private String projectAppIdent;
	private String bnewellCustname;
	private Boolean flatPanel;
	private String updateUser;
	private Integer quoteId;
	private Short quoteVersion;
	private String quotePrjname;
	private String amsRequest;
	private Date insertDate;
	private String auditFlg;
	private String printOptionFlg;
	private String originatingAmsnumber;
	private String insertUser;
	private Date updateDate;
	private String licenseUsage;
	private String warrantyFlg;
	private String oemFlg;
	private String imcSerialFlg;
	private Short projectTypeId;
	private Short projectActivityId;
	private String thirdPartyIntFl;
	private String thirdPartyIntName;
	private String lockedFl;
	private String lockedBy;
	private String waiverFl;
	private String waiverId;
	private String waiverScn;
	private BigDecimal businessProcessId;
	private int itsTeamId;
	private String shipmentScheduledFl;
	private String avnetQuoteNo;
	private BigDecimal bomTypeId;
	private BigDecimal compareableTypeId;
	private BigDecimal currentAmsQuoteId;
	private BigDecimal currentPlcId;
	private String dealNo;
	private String orderableOnHoldFl;
	private String quoteRequestNo;
	private String r2oQuoteNo;
	private String tipsNo;
	private String logicalDeleteFl;
	private String endusername;
	private String recordNo;
	private String exportComplianceFl;
	private Date osiRequestDt;
	private BigDecimal osiFeeAm;
	private String osiRequestTm;
	private BigDecimal projectCategoryId;
	private String planConsumptionWarehouseCd;
	private String erpPartNumber;
	private String vendorMaterialNo;
	private Integer sourceErpId;
	private BigDecimal originatingProjectId;
	private String govRatedOrderFl;
	private String govPriorityRatingCd;
	private String fgiFl;
	private String sourceInspectionFl;
	private Date lastProducedDt;
	private String rackServiceFl;
	private String tlaMfgCd;
	private String tlaCommCd;
	private String tlaGroupCd;
	private BigDecimal cooAssessmentTypeId;
	private String bindingRulesExistFl;
	private String bindingRuleNo;
	private String bindingRuleCommentTx;
	private String exportComplianceRequiredFl;
	private String bomInstructionCd;
	private BigDecimal cooAssessmentQuestionId;
	private String tlaReadyFl;

	public Project() {
	}

	public Project(BigDecimal projectId, String custno, String amsnumber,
			String projectAppIdent, String insertUser,
			BigDecimal businessProcessId, int itsTeamId,
			String shipmentScheduledFl, String orderableOnHoldFl,
			String logicalDeleteFl, String govRatedOrderFl, String tlaReadyFl) {
		this.projectId = projectId;
		this.custno = custno;
		this.amsnumber = amsnumber;
		this.projectAppIdent = projectAppIdent;
		this.insertUser = insertUser;
		this.businessProcessId = businessProcessId;
		this.itsTeamId = itsTeamId;
		this.shipmentScheduledFl = shipmentScheduledFl;
		this.orderableOnHoldFl = orderableOnHoldFl;
		this.logicalDeleteFl = logicalDeleteFl;
		this.govRatedOrderFl = govRatedOrderFl;
		this.tlaReadyFl = tlaReadyFl;
	}

	public Project(BigDecimal projectId, String custno, String companyname,
			String custrevisionno, String projectdesc, String custpartno,
			Integer productionqty, Integer runrate, BigDecimal margin,
			BigDecimal systemcost, Character approvalflag, String instructions,
			String aacRevisionNum, String integrationType, String scope,
			String amsnumber, String projectName, String activity,
			String status, Date protoRequiredDate, Date protoMaterialrecdate,
			Date protoShipdate, Date protoScheddate, String protoLocation,
			String buildFacilityName, Boolean hardwareOnly,
			Boolean buildFromParts, Boolean requireImage, Boolean specialLabel,
			Boolean specialBox, BigDecimal difficultyLevel, String clientNotes,
			String projectAppIdent, String bnewellCustname, Boolean flatPanel,
			String updateUser, Integer quoteId, Short quoteVersion,
			String quotePrjname, String amsRequest, Date insertDate,
			String auditFlg, String printOptionFlg,
			String originatingAmsnumber, String insertUser, Date updateDate,
			String licenseUsage, String warrantyFlg, String oemFlg,
			String imcSerialFlg, Short projectTypeId, Short projectActivityId,
			String thirdPartyIntFl, String thirdPartyIntName, String lockedFl,
			String lockedBy, String waiverFl, String waiverId,
			String waiverScn, BigDecimal businessProcessId, int itsTeamId,
			String shipmentScheduledFl, String avnetQuoteNo,
			BigDecimal bomTypeId, BigDecimal compareableTypeId,
			BigDecimal currentAmsQuoteId, BigDecimal currentPlcId,
			String dealNo, String orderableOnHoldFl, String quoteRequestNo,
			String r2oQuoteNo, String tipsNo, String logicalDeleteFl,
			String endusername, String recordNo, String exportComplianceFl,
			Date osiRequestDt, BigDecimal osiFeeAm, String osiRequestTm,
			BigDecimal projectCategoryId, String planConsumptionWarehouseCd,
			String erpPartNumber, String vendorMaterialNo, Integer sourceErpId,
			BigDecimal originatingProjectId, String govRatedOrderFl,
			String govPriorityRatingCd, String fgiFl,
			String sourceInspectionFl, Date lastProducedDt,
			String rackServiceFl, String tlaMfgCd, String tlaCommCd,
			String tlaGroupCd, BigDecimal cooAssessmentTypeId,
			String bindingRulesExistFl, String bindingRuleNo,
			String bindingRuleCommentTx, String exportComplianceRequiredFl,
			String bomInstructionCd, BigDecimal cooAssessmentQuestionId,
			String tlaReadyFl) {
		this.projectId = projectId;
		this.custno = custno;
		this.companyname = companyname;
		this.custrevisionno = custrevisionno;
		this.projectdesc = projectdesc;
		this.custpartno = custpartno;
		this.productionqty = productionqty;
		this.runrate = runrate;
		this.margin = margin;
		this.systemcost = systemcost;
		this.approvalflag = approvalflag;
		this.instructions = instructions;
		this.aacRevisionNum = aacRevisionNum;
		this.integrationType = integrationType;
		this.scope = scope;
		this.amsnumber = amsnumber;
		this.projectName = projectName;
		this.activity = activity;
		this.status = status;
		this.protoRequiredDate = protoRequiredDate;
		this.protoMaterialrecdate = protoMaterialrecdate;
		this.protoShipdate = protoShipdate;
		this.protoScheddate = protoScheddate;
		this.protoLocation = protoLocation;
		this.buildFacilityName = buildFacilityName;
		this.hardwareOnly = hardwareOnly;
		this.buildFromParts = buildFromParts;
		this.requireImage = requireImage;
		this.specialLabel = specialLabel;
		this.specialBox = specialBox;
		this.difficultyLevel = difficultyLevel;
		this.clientNotes = clientNotes;
		this.projectAppIdent = projectAppIdent;
		this.bnewellCustname = bnewellCustname;
		this.flatPanel = flatPanel;
		this.updateUser = updateUser;
		this.quoteId = quoteId;
		this.quoteVersion = quoteVersion;
		this.quotePrjname = quotePrjname;
		this.amsRequest = amsRequest;
		this.insertDate = insertDate;
		this.auditFlg = auditFlg;
		this.printOptionFlg = printOptionFlg;
		this.originatingAmsnumber = originatingAmsnumber;
		this.insertUser = insertUser;
		this.updateDate = updateDate;
		this.licenseUsage = licenseUsage;
		this.warrantyFlg = warrantyFlg;
		this.oemFlg = oemFlg;
		this.imcSerialFlg = imcSerialFlg;
		this.projectTypeId = projectTypeId;
		this.projectActivityId = projectActivityId;
		this.thirdPartyIntFl = thirdPartyIntFl;
		this.thirdPartyIntName = thirdPartyIntName;
		this.lockedFl = lockedFl;
		this.lockedBy = lockedBy;
		this.waiverFl = waiverFl;
		this.waiverId = waiverId;
		this.waiverScn = waiverScn;
		this.businessProcessId = businessProcessId;
		this.itsTeamId = itsTeamId;
		this.shipmentScheduledFl = shipmentScheduledFl;
		this.avnetQuoteNo = avnetQuoteNo;
		this.bomTypeId = bomTypeId;
		this.compareableTypeId = compareableTypeId;
		this.currentAmsQuoteId = currentAmsQuoteId;
		this.currentPlcId = currentPlcId;
		this.dealNo = dealNo;
		this.orderableOnHoldFl = orderableOnHoldFl;
		this.quoteRequestNo = quoteRequestNo;
		this.r2oQuoteNo = r2oQuoteNo;
		this.tipsNo = tipsNo;
		this.logicalDeleteFl = logicalDeleteFl;
		this.endusername = endusername;
		this.recordNo = recordNo;
		this.exportComplianceFl = exportComplianceFl;
		this.osiRequestDt = osiRequestDt;
		this.osiFeeAm = osiFeeAm;
		this.osiRequestTm = osiRequestTm;
		this.projectCategoryId = projectCategoryId;
		this.planConsumptionWarehouseCd = planConsumptionWarehouseCd;
		this.erpPartNumber = erpPartNumber;
		this.vendorMaterialNo = vendorMaterialNo;
		this.sourceErpId = sourceErpId;
		this.originatingProjectId = originatingProjectId;
		this.govRatedOrderFl = govRatedOrderFl;
		this.govPriorityRatingCd = govPriorityRatingCd;
		this.fgiFl = fgiFl;
		this.sourceInspectionFl = sourceInspectionFl;
		this.lastProducedDt = lastProducedDt;
		this.rackServiceFl = rackServiceFl;
		this.tlaMfgCd = tlaMfgCd;
		this.tlaCommCd = tlaCommCd;
		this.tlaGroupCd = tlaGroupCd;
		this.cooAssessmentTypeId = cooAssessmentTypeId;
		this.bindingRulesExistFl = bindingRulesExistFl;
		this.bindingRuleNo = bindingRuleNo;
		this.bindingRuleCommentTx = bindingRuleCommentTx;
		this.exportComplianceRequiredFl = exportComplianceRequiredFl;
		this.bomInstructionCd = bomInstructionCd;
		this.cooAssessmentQuestionId = cooAssessmentQuestionId;
		this.tlaReadyFl = tlaReadyFl;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public String getCustno() {
		return this.custno;
	}

	public void setCustno(String custno) {
		this.custno = custno;
	}

	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getCustrevisionno() {
		return this.custrevisionno;
	}

	public void setCustrevisionno(String custrevisionno) {
		this.custrevisionno = custrevisionno;
	}

	public String getProjectdesc() {
		return this.projectdesc;
	}

	public void setProjectdesc(String projectdesc) {
		this.projectdesc = projectdesc;
	}

	public String getCustpartno() {
		return this.custpartno;
	}

	public void setCustpartno(String custpartno) {
		this.custpartno = custpartno;
	}

	public Integer getProductionqty() {
		return this.productionqty;
	}

	public void setProductionqty(Integer productionqty) {
		this.productionqty = productionqty;
	}

	public Integer getRunrate() {
		return this.runrate;
	}

	public void setRunrate(Integer runrate) {
		this.runrate = runrate;
	}

	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	public BigDecimal getSystemcost() {
		return this.systemcost;
	}

	public void setSystemcost(BigDecimal systemcost) {
		this.systemcost = systemcost;
	}

	public Character getApprovalflag() {
		return this.approvalflag;
	}

	public void setApprovalflag(Character approvalflag) {
		this.approvalflag = approvalflag;
	}

	public String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(String instructions) {
		this.instructions = instructions;
	}

	public String getAacRevisionNum() {
		return this.aacRevisionNum;
	}

	public void setAacRevisionNum(String aacRevisionNum) {
		this.aacRevisionNum = aacRevisionNum;
	}

	public String getIntegrationType() {
		return this.integrationType;
	}

	public void setIntegrationType(String integrationType) {
		this.integrationType = integrationType;
	}

	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public String getAmsnumber() {
		return this.amsnumber;
	}

	public void setAmsnumber(String amsnumber) {
		this.amsnumber = amsnumber;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getProtoRequiredDate() {
		return this.protoRequiredDate;
	}

	public void setProtoRequiredDate(Date protoRequiredDate) {
		this.protoRequiredDate = protoRequiredDate;
	}

	public Date getProtoMaterialrecdate() {
		return this.protoMaterialrecdate;
	}

	public void setProtoMaterialrecdate(Date protoMaterialrecdate) {
		this.protoMaterialrecdate = protoMaterialrecdate;
	}

	public Date getProtoShipdate() {
		return this.protoShipdate;
	}

	public void setProtoShipdate(Date protoShipdate) {
		this.protoShipdate = protoShipdate;
	}

	public Date getProtoScheddate() {
		return this.protoScheddate;
	}

	public void setProtoScheddate(Date protoScheddate) {
		this.protoScheddate = protoScheddate;
	}

	public String getProtoLocation() {
		return this.protoLocation;
	}

	public void setProtoLocation(String protoLocation) {
		this.protoLocation = protoLocation;
	}

	public String getBuildFacilityName() {
		return this.buildFacilityName;
	}

	public void setBuildFacilityName(String buildFacilityName) {
		this.buildFacilityName = buildFacilityName;
	}

	public Boolean getHardwareOnly() {
		return this.hardwareOnly;
	}

	public void setHardwareOnly(Boolean hardwareOnly) {
		this.hardwareOnly = hardwareOnly;
	}

	public Boolean getBuildFromParts() {
		return this.buildFromParts;
	}

	public void setBuildFromParts(Boolean buildFromParts) {
		this.buildFromParts = buildFromParts;
	}

	public Boolean getRequireImage() {
		return this.requireImage;
	}

	public void setRequireImage(Boolean requireImage) {
		this.requireImage = requireImage;
	}

	public Boolean getSpecialLabel() {
		return this.specialLabel;
	}

	public void setSpecialLabel(Boolean specialLabel) {
		this.specialLabel = specialLabel;
	}

	public Boolean getSpecialBox() {
		return this.specialBox;
	}

	public void setSpecialBox(Boolean specialBox) {
		this.specialBox = specialBox;
	}

	public BigDecimal getDifficultyLevel() {
		return this.difficultyLevel;
	}

	public void setDifficultyLevel(BigDecimal difficultyLevel) {
		this.difficultyLevel = difficultyLevel;
	}

	public String getClientNotes() {
		return this.clientNotes;
	}

	public void setClientNotes(String clientNotes) {
		this.clientNotes = clientNotes;
	}

	public String getProjectAppIdent() {
		return this.projectAppIdent;
	}

	public void setProjectAppIdent(String projectAppIdent) {
		this.projectAppIdent = projectAppIdent;
	}

	public String getBnewellCustname() {
		return this.bnewellCustname;
	}

	public void setBnewellCustname(String bnewellCustname) {
		this.bnewellCustname = bnewellCustname;
	}

	public Boolean getFlatPanel() {
		return this.flatPanel;
	}

	public void setFlatPanel(Boolean flatPanel) {
		this.flatPanel = flatPanel;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Integer getQuoteId() {
		return this.quoteId;
	}

	public void setQuoteId(Integer quoteId) {
		this.quoteId = quoteId;
	}

	public Short getQuoteVersion() {
		return this.quoteVersion;
	}

	public void setQuoteVersion(Short quoteVersion) {
		this.quoteVersion = quoteVersion;
	}

	public String getQuotePrjname() {
		return this.quotePrjname;
	}

	public void setQuotePrjname(String quotePrjname) {
		this.quotePrjname = quotePrjname;
	}

	public String getAmsRequest() {
		return this.amsRequest;
	}

	public void setAmsRequest(String amsRequest) {
		this.amsRequest = amsRequest;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getAuditFlg() {
		return this.auditFlg;
	}

	public void setAuditFlg(String auditFlg) {
		this.auditFlg = auditFlg;
	}

	public String getPrintOptionFlg() {
		return this.printOptionFlg;
	}

	public void setPrintOptionFlg(String printOptionFlg) {
		this.printOptionFlg = printOptionFlg;
	}

	public String getOriginatingAmsnumber() {
		return this.originatingAmsnumber;
	}

	public void setOriginatingAmsnumber(String originatingAmsnumber) {
		this.originatingAmsnumber = originatingAmsnumber;
	}

	public String getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getLicenseUsage() {
		return this.licenseUsage;
	}

	public void setLicenseUsage(String licenseUsage) {
		this.licenseUsage = licenseUsage;
	}

	public String getWarrantyFlg() {
		return this.warrantyFlg;
	}

	public void setWarrantyFlg(String warrantyFlg) {
		this.warrantyFlg = warrantyFlg;
	}

	public String getOemFlg() {
		return this.oemFlg;
	}

	public void setOemFlg(String oemFlg) {
		this.oemFlg = oemFlg;
	}

	public String getImcSerialFlg() {
		return this.imcSerialFlg;
	}

	public void setImcSerialFlg(String imcSerialFlg) {
		this.imcSerialFlg = imcSerialFlg;
	}

	public Short getProjectTypeId() {
		return this.projectTypeId;
	}

	public void setProjectTypeId(Short projectTypeId) {
		this.projectTypeId = projectTypeId;
	}

	public Short getProjectActivityId() {
		return this.projectActivityId;
	}

	public void setProjectActivityId(Short projectActivityId) {
		this.projectActivityId = projectActivityId;
	}

	public String getThirdPartyIntFl() {
		return this.thirdPartyIntFl;
	}

	public void setThirdPartyIntFl(String thirdPartyIntFl) {
		this.thirdPartyIntFl = thirdPartyIntFl;
	}

	public String getThirdPartyIntName() {
		return this.thirdPartyIntName;
	}

	public void setThirdPartyIntName(String thirdPartyIntName) {
		this.thirdPartyIntName = thirdPartyIntName;
	}

	public String getLockedFl() {
		return this.lockedFl;
	}

	public void setLockedFl(String lockedFl) {
		this.lockedFl = lockedFl;
	}

	public String getLockedBy() {
		return this.lockedBy;
	}

	public void setLockedBy(String lockedBy) {
		this.lockedBy = lockedBy;
	}

	public String getWaiverFl() {
		return this.waiverFl;
	}

	public void setWaiverFl(String waiverFl) {
		this.waiverFl = waiverFl;
	}

	public String getWaiverId() {
		return this.waiverId;
	}

	public void setWaiverId(String waiverId) {
		this.waiverId = waiverId;
	}

	public String getWaiverScn() {
		return this.waiverScn;
	}

	public void setWaiverScn(String waiverScn) {
		this.waiverScn = waiverScn;
	}

	public BigDecimal getBusinessProcessId() {
		return this.businessProcessId;
	}

	public void setBusinessProcessId(BigDecimal businessProcessId) {
		this.businessProcessId = businessProcessId;
	}

	public int getItsTeamId() {
		return this.itsTeamId;
	}

	public void setItsTeamId(int itsTeamId) {
		this.itsTeamId = itsTeamId;
	}

	public String getShipmentScheduledFl() {
		return this.shipmentScheduledFl;
	}

	public void setShipmentScheduledFl(String shipmentScheduledFl) {
		this.shipmentScheduledFl = shipmentScheduledFl;
	}

	public String getAvnetQuoteNo() {
		return this.avnetQuoteNo;
	}

	public void setAvnetQuoteNo(String avnetQuoteNo) {
		this.avnetQuoteNo = avnetQuoteNo;
	}

	public BigDecimal getBomTypeId() {
		return this.bomTypeId;
	}

	public void setBomTypeId(BigDecimal bomTypeId) {
		this.bomTypeId = bomTypeId;
	}

	public BigDecimal getCompareableTypeId() {
		return this.compareableTypeId;
	}

	public void setCompareableTypeId(BigDecimal compareableTypeId) {
		this.compareableTypeId = compareableTypeId;
	}

	public BigDecimal getCurrentAmsQuoteId() {
		return this.currentAmsQuoteId;
	}

	public void setCurrentAmsQuoteId(BigDecimal currentAmsQuoteId) {
		this.currentAmsQuoteId = currentAmsQuoteId;
	}

	public BigDecimal getCurrentPlcId() {
		return this.currentPlcId;
	}

	public void setCurrentPlcId(BigDecimal currentPlcId) {
		this.currentPlcId = currentPlcId;
	}

	public String getDealNo() {
		return this.dealNo;
	}

	public void setDealNo(String dealNo) {
		this.dealNo = dealNo;
	}

	public String getOrderableOnHoldFl() {
		return this.orderableOnHoldFl;
	}

	public void setOrderableOnHoldFl(String orderableOnHoldFl) {
		this.orderableOnHoldFl = orderableOnHoldFl;
	}

	public String getQuoteRequestNo() {
		return this.quoteRequestNo;
	}

	public void setQuoteRequestNo(String quoteRequestNo) {
		this.quoteRequestNo = quoteRequestNo;
	}

	public String getR2oQuoteNo() {
		return this.r2oQuoteNo;
	}

	public void setR2oQuoteNo(String r2oQuoteNo) {
		this.r2oQuoteNo = r2oQuoteNo;
	}

	public String getTipsNo() {
		return this.tipsNo;
	}

	public void setTipsNo(String tipsNo) {
		this.tipsNo = tipsNo;
	}

	public String getLogicalDeleteFl() {
		return this.logicalDeleteFl;
	}

	public void setLogicalDeleteFl(String logicalDeleteFl) {
		this.logicalDeleteFl = logicalDeleteFl;
	}

	public String getEndusername() {
		return this.endusername;
	}

	public void setEndusername(String endusername) {
		this.endusername = endusername;
	}

	public String getRecordNo() {
		return this.recordNo;
	}

	public void setRecordNo(String recordNo) {
		this.recordNo = recordNo;
	}

	public String getExportComplianceFl() {
		return this.exportComplianceFl;
	}

	public void setExportComplianceFl(String exportComplianceFl) {
		this.exportComplianceFl = exportComplianceFl;
	}

	public Date getOsiRequestDt() {
		return this.osiRequestDt;
	}

	public void setOsiRequestDt(Date osiRequestDt) {
		this.osiRequestDt = osiRequestDt;
	}

	public BigDecimal getOsiFeeAm() {
		return this.osiFeeAm;
	}

	public void setOsiFeeAm(BigDecimal osiFeeAm) {
		this.osiFeeAm = osiFeeAm;
	}

	public String getOsiRequestTm() {
		return this.osiRequestTm;
	}

	public void setOsiRequestTm(String osiRequestTm) {
		this.osiRequestTm = osiRequestTm;
	}

	public BigDecimal getProjectCategoryId() {
		return this.projectCategoryId;
	}

	public void setProjectCategoryId(BigDecimal projectCategoryId) {
		this.projectCategoryId = projectCategoryId;
	}

	public String getPlanConsumptionWarehouseCd() {
		return this.planConsumptionWarehouseCd;
	}

	public void setPlanConsumptionWarehouseCd(String planConsumptionWarehouseCd) {
		this.planConsumptionWarehouseCd = planConsumptionWarehouseCd;
	}

	public String getErpPartNumber() {
		return this.erpPartNumber;
	}

	public void setErpPartNumber(String erpPartNumber) {
		this.erpPartNumber = erpPartNumber;
	}

	public String getVendorMaterialNo() {
		return this.vendorMaterialNo;
	}

	public void setVendorMaterialNo(String vendorMaterialNo) {
		this.vendorMaterialNo = vendorMaterialNo;
	}

	public Integer getSourceErpId() {
		return this.sourceErpId;
	}

	public void setSourceErpId(Integer sourceErpId) {
		this.sourceErpId = sourceErpId;
	}

	public BigDecimal getOriginatingProjectId() {
		return this.originatingProjectId;
	}

	public void setOriginatingProjectId(BigDecimal originatingProjectId) {
		this.originatingProjectId = originatingProjectId;
	}

	public String getGovRatedOrderFl() {
		return this.govRatedOrderFl;
	}

	public void setGovRatedOrderFl(String govRatedOrderFl) {
		this.govRatedOrderFl = govRatedOrderFl;
	}

	public String getGovPriorityRatingCd() {
		return this.govPriorityRatingCd;
	}

	public void setGovPriorityRatingCd(String govPriorityRatingCd) {
		this.govPriorityRatingCd = govPriorityRatingCd;
	}

	public String getFgiFl() {
		return this.fgiFl;
	}

	public void setFgiFl(String fgiFl) {
		this.fgiFl = fgiFl;
	}

	public String getSourceInspectionFl() {
		return this.sourceInspectionFl;
	}

	public void setSourceInspectionFl(String sourceInspectionFl) {
		this.sourceInspectionFl = sourceInspectionFl;
	}

	public Date getLastProducedDt() {
		return this.lastProducedDt;
	}

	public void setLastProducedDt(Date lastProducedDt) {
		this.lastProducedDt = lastProducedDt;
	}

	public String getRackServiceFl() {
		return this.rackServiceFl;
	}

	public void setRackServiceFl(String rackServiceFl) {
		this.rackServiceFl = rackServiceFl;
	}

	public String getTlaMfgCd() {
		return this.tlaMfgCd;
	}

	public void setTlaMfgCd(String tlaMfgCd) {
		this.tlaMfgCd = tlaMfgCd;
	}

	public String getTlaCommCd() {
		return this.tlaCommCd;
	}

	public void setTlaCommCd(String tlaCommCd) {
		this.tlaCommCd = tlaCommCd;
	}

	public String getTlaGroupCd() {
		return this.tlaGroupCd;
	}

	public void setTlaGroupCd(String tlaGroupCd) {
		this.tlaGroupCd = tlaGroupCd;
	}

	public BigDecimal getCooAssessmentTypeId() {
		return this.cooAssessmentTypeId;
	}

	public void setCooAssessmentTypeId(BigDecimal cooAssessmentTypeId) {
		this.cooAssessmentTypeId = cooAssessmentTypeId;
	}

	public String getBindingRulesExistFl() {
		return this.bindingRulesExistFl;
	}

	public void setBindingRulesExistFl(String bindingRulesExistFl) {
		this.bindingRulesExistFl = bindingRulesExistFl;
	}

	public String getBindingRuleNo() {
		return this.bindingRuleNo;
	}

	public void setBindingRuleNo(String bindingRuleNo) {
		this.bindingRuleNo = bindingRuleNo;
	}

	public String getBindingRuleCommentTx() {
		return this.bindingRuleCommentTx;
	}

	public void setBindingRuleCommentTx(String bindingRuleCommentTx) {
		this.bindingRuleCommentTx = bindingRuleCommentTx;
	}

	public String getExportComplianceRequiredFl() {
		return this.exportComplianceRequiredFl;
	}

	public void setExportComplianceRequiredFl(String exportComplianceRequiredFl) {
		this.exportComplianceRequiredFl = exportComplianceRequiredFl;
	}

	public String getBomInstructionCd() {
		return this.bomInstructionCd;
	}

	public void setBomInstructionCd(String bomInstructionCd) {
		this.bomInstructionCd = bomInstructionCd;
	}

	public BigDecimal getCooAssessmentQuestionId() {
		return this.cooAssessmentQuestionId;
	}

	public void setCooAssessmentQuestionId(BigDecimal cooAssessmentQuestionId) {
		this.cooAssessmentQuestionId = cooAssessmentQuestionId;
	}

	public String getTlaReadyFl() {
		return this.tlaReadyFl;
	}

	public void setTlaReadyFl(String tlaReadyFl) {
		this.tlaReadyFl = tlaReadyFl;
	}

}
