package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ContactGroupMember generated by hbm2java
 */
public class ContactGroupMember implements java.io.Serializable {

	private BigDecimal contactGroupMemberId;
	private Contact contact;
	private ContactGroup contactGroup;
	private Date createDt;
	private BigDecimal createUserId;
	private BigDecimal updateUserId;
	private Date updateDt;

	public ContactGroupMember() {
	}

	public ContactGroupMember(BigDecimal contactGroupMemberId, Contact contact,
			ContactGroup contactGroup, Date createDt, BigDecimal createUserId,
			BigDecimal updateUserId, Date updateDt) {
		this.contactGroupMemberId = contactGroupMemberId;
		this.contact = contact;
		this.contactGroup = contactGroup;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.updateUserId = updateUserId;
		this.updateDt = updateDt;
	}

	public BigDecimal getContactGroupMemberId() {
		return this.contactGroupMemberId;
	}

	public void setContactGroupMemberId(BigDecimal contactGroupMemberId) {
		this.contactGroupMemberId = contactGroupMemberId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public ContactGroup getContactGroup() {
		return this.contactGroup;
	}

	public void setContactGroup(ContactGroup contactGroup) {
		this.contactGroup = contactGroup;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

}
