package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private BigDecimal contactId;
	private Site site;
	private String contactNm;
	private Date createDt;
	private BigDecimal createUserId;
	private String defaultEmailAddressTx;
	private BigDecimal defaultPostalAddressId;
	private String firstNm;
	private String lastNm;
	private String mobilePhoneNo;
	private BigDecimal languageId;
	private BigDecimal preferredLanguageId;
	private Date updateDt;
	private BigDecimal updateUserId;
	private String workFaxNo;
	private String workPhoneNo;
	private String titleTx;
	private String federalExpressAccountNo;
	private Set userContacts = new HashSet(0);
	private Set contactGroupMembers = new HashSet(0);
	private Set userses = new HashSet(0);

	public Contact() {
	}

	public Contact(BigDecimal contactId, Date createDt,
			BigDecimal createUserId, BigDecimal languageId, Date updateDt,
			BigDecimal updateUserId) {
		this.contactId = contactId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.languageId = languageId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public Contact(BigDecimal contactId, Site site, String contactNm,
			Date createDt, BigDecimal createUserId,
			String defaultEmailAddressTx, BigDecimal defaultPostalAddressId,
			String firstNm, String lastNm, String mobilePhoneNo,
			BigDecimal languageId, BigDecimal preferredLanguageId,
			Date updateDt, BigDecimal updateUserId, String workFaxNo,
			String workPhoneNo, String titleTx, String federalExpressAccountNo,
			Set userContacts, Set contactGroupMembers, Set userses) {
		this.contactId = contactId;
		this.site = site;
		this.contactNm = contactNm;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.defaultEmailAddressTx = defaultEmailAddressTx;
		this.defaultPostalAddressId = defaultPostalAddressId;
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.mobilePhoneNo = mobilePhoneNo;
		this.languageId = languageId;
		this.preferredLanguageId = preferredLanguageId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.workFaxNo = workFaxNo;
		this.workPhoneNo = workPhoneNo;
		this.titleTx = titleTx;
		this.federalExpressAccountNo = federalExpressAccountNo;
		this.userContacts = userContacts;
		this.contactGroupMembers = contactGroupMembers;
		this.userses = userses;
	}

	public BigDecimal getContactId() {
		return this.contactId;
	}

	public void setContactId(BigDecimal contactId) {
		this.contactId = contactId;
	}

	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	public String getContactNm() {
		return this.contactNm;
	}

	public void setContactNm(String contactNm) {
		this.contactNm = contactNm;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getDefaultEmailAddressTx() {
		return this.defaultEmailAddressTx;
	}

	public void setDefaultEmailAddressTx(String defaultEmailAddressTx) {
		this.defaultEmailAddressTx = defaultEmailAddressTx;
	}

	public BigDecimal getDefaultPostalAddressId() {
		return this.defaultPostalAddressId;
	}

	public void setDefaultPostalAddressId(BigDecimal defaultPostalAddressId) {
		this.defaultPostalAddressId = defaultPostalAddressId;
	}

	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	public String getMobilePhoneNo() {
		return this.mobilePhoneNo;
	}

	public void setMobilePhoneNo(String mobilePhoneNo) {
		this.mobilePhoneNo = mobilePhoneNo;
	}

	public BigDecimal getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(BigDecimal languageId) {
		this.languageId = languageId;
	}

	public BigDecimal getPreferredLanguageId() {
		return this.preferredLanguageId;
	}

	public void setPreferredLanguageId(BigDecimal preferredLanguageId) {
		this.preferredLanguageId = preferredLanguageId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public String getWorkFaxNo() {
		return this.workFaxNo;
	}

	public void setWorkFaxNo(String workFaxNo) {
		this.workFaxNo = workFaxNo;
	}

	public String getWorkPhoneNo() {
		return this.workPhoneNo;
	}

	public void setWorkPhoneNo(String workPhoneNo) {
		this.workPhoneNo = workPhoneNo;
	}

	public String getTitleTx() {
		return this.titleTx;
	}

	public void setTitleTx(String titleTx) {
		this.titleTx = titleTx;
	}

	public String getFederalExpressAccountNo() {
		return this.federalExpressAccountNo;
	}

	public void setFederalExpressAccountNo(String federalExpressAccountNo) {
		this.federalExpressAccountNo = federalExpressAccountNo;
	}

	public Set getUserContacts() {
		return this.userContacts;
	}

	public void setUserContacts(Set userContacts) {
		this.userContacts = userContacts;
	}

	public Set getContactGroupMembers() {
		return this.contactGroupMembers;
	}

	public void setContactGroupMembers(Set contactGroupMembers) {
		this.contactGroupMembers = contactGroupMembers;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
