package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContactType generated by hbm2java
 */
public class ContactType implements java.io.Serializable {

	private BigDecimal contactTypeId;
	private String contactTypeCd;
	private String contactTypeNm;
	private Date createDt;
	private BigDecimal createUserId;
	private Date updateDt;
	private BigDecimal updateUserId;
	private Set userContacts = new HashSet(0);

	public ContactType() {
	}

	public ContactType(BigDecimal contactTypeId, String contactTypeCd,
			String contactTypeNm, Date createDt, BigDecimal createUserId,
			Date updateDt, BigDecimal updateUserId) {
		this.contactTypeId = contactTypeId;
		this.contactTypeCd = contactTypeCd;
		this.contactTypeNm = contactTypeNm;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public ContactType(BigDecimal contactTypeId, String contactTypeCd,
			String contactTypeNm, Date createDt, BigDecimal createUserId,
			Date updateDt, BigDecimal updateUserId, Set userContacts) {
		this.contactTypeId = contactTypeId;
		this.contactTypeCd = contactTypeCd;
		this.contactTypeNm = contactTypeNm;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.userContacts = userContacts;
	}

	public BigDecimal getContactTypeId() {
		return this.contactTypeId;
	}

	public void setContactTypeId(BigDecimal contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	public String getContactTypeCd() {
		return this.contactTypeCd;
	}

	public void setContactTypeCd(String contactTypeCd) {
		this.contactTypeCd = contactTypeCd;
	}

	public String getContactTypeNm() {
		return this.contactTypeNm;
	}

	public void setContactTypeNm(String contactTypeNm) {
		this.contactTypeNm = contactTypeNm;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Set getUserContacts() {
		return this.userContacts;
	}

	public void setUserContacts(Set userContacts) {
		this.userContacts = userContacts;
	}

}
