package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContactGroup generated by hbm2java
 */
public class ContactGroup implements java.io.Serializable {

	private BigDecimal contactGroupId;
	private Date createDt;
	private BigDecimal createUserId;
	private String groupDs;
	private String groupEmailAddressTx;
	private String groupNm;
	private BigDecimal updateUserId;
	private Date updateDt;
	private Set contactGroupMembers = new HashSet(0);

	public ContactGroup() {
	}

	public ContactGroup(BigDecimal contactGroupId, Date createDt,
			BigDecimal createUserId, String groupNm, BigDecimal updateUserId,
			Date updateDt) {
		this.contactGroupId = contactGroupId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.groupNm = groupNm;
		this.updateUserId = updateUserId;
		this.updateDt = updateDt;
	}

	public ContactGroup(BigDecimal contactGroupId, Date createDt,
			BigDecimal createUserId, String groupDs,
			String groupEmailAddressTx, String groupNm,
			BigDecimal updateUserId, Date updateDt, Set contactGroupMembers) {
		this.contactGroupId = contactGroupId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.groupDs = groupDs;
		this.groupEmailAddressTx = groupEmailAddressTx;
		this.groupNm = groupNm;
		this.updateUserId = updateUserId;
		this.updateDt = updateDt;
		this.contactGroupMembers = contactGroupMembers;
	}

	public BigDecimal getContactGroupId() {
		return this.contactGroupId;
	}

	public void setContactGroupId(BigDecimal contactGroupId) {
		this.contactGroupId = contactGroupId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getGroupDs() {
		return this.groupDs;
	}

	public void setGroupDs(String groupDs) {
		this.groupDs = groupDs;
	}

	public String getGroupEmailAddressTx() {
		return this.groupEmailAddressTx;
	}

	public void setGroupEmailAddressTx(String groupEmailAddressTx) {
		this.groupEmailAddressTx = groupEmailAddressTx;
	}

	public String getGroupNm() {
		return this.groupNm;
	}

	public void setGroupNm(String groupNm) {
		this.groupNm = groupNm;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public Set getContactGroupMembers() {
		return this.contactGroupMembers;
	}

	public void setContactGroupMembers(Set contactGroupMembers) {
		this.contactGroupMembers = contactGroupMembers;
	}

}
