package com.avnet.alapps.model.gsfc;

// Generated Aug 18, 2016 3:39:01 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private BigDecimal countryId;
	private Date createDt;
	private BigDecimal createUserId;
	private String countryIsoAlpha2Cd;
	private String countryIsoAlpha3Cd;
	private String countryIsoNo;
	private String countryNm;
	private Date updateDt;
	private BigDecimal updateUserId;
	private BigDecimal globalRegionId;

	public Country() {
	}

	public Country(BigDecimal countryId, Date createDt,
			BigDecimal createUserId, String countryIsoAlpha2Cd,
			String countryIsoAlpha3Cd, String countryIsoNo, String countryNm,
			Date updateDt, BigDecimal updateUserId) {
		this.countryId = countryId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.countryIsoAlpha2Cd = countryIsoAlpha2Cd;
		this.countryIsoAlpha3Cd = countryIsoAlpha3Cd;
		this.countryIsoNo = countryIsoNo;
		this.countryNm = countryNm;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public Country(BigDecimal countryId, Date createDt,
			BigDecimal createUserId, String countryIsoAlpha2Cd,
			String countryIsoAlpha3Cd, String countryIsoNo, String countryNm,
			Date updateDt, BigDecimal updateUserId, BigDecimal globalRegionId) {
		this.countryId = countryId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.countryIsoAlpha2Cd = countryIsoAlpha2Cd;
		this.countryIsoAlpha3Cd = countryIsoAlpha3Cd;
		this.countryIsoNo = countryIsoNo;
		this.countryNm = countryNm;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.globalRegionId = globalRegionId;
	}

	public BigDecimal getCountryId() {
		return this.countryId;
	}

	public void setCountryId(BigDecimal countryId) {
		this.countryId = countryId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getCountryIsoAlpha2Cd() {
		return this.countryIsoAlpha2Cd;
	}

	public void setCountryIsoAlpha2Cd(String countryIsoAlpha2Cd) {
		this.countryIsoAlpha2Cd = countryIsoAlpha2Cd;
	}

	public String getCountryIsoAlpha3Cd() {
		return this.countryIsoAlpha3Cd;
	}

	public void setCountryIsoAlpha3Cd(String countryIsoAlpha3Cd) {
		this.countryIsoAlpha3Cd = countryIsoAlpha3Cd;
	}

	public String getCountryIsoNo() {
		return this.countryIsoNo;
	}

	public void setCountryIsoNo(String countryIsoNo) {
		this.countryIsoNo = countryIsoNo;
	}

	public String getCountryNm() {
		return this.countryNm;
	}

	public void setCountryNm(String countryNm) {
		this.countryNm = countryNm;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public BigDecimal getGlobalRegionId() {
		return this.globalRegionId;
	}

	public void setGlobalRegionId(BigDecimal globalRegionId) {
		this.globalRegionId = globalRegionId;
	}

}
