package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UpromHost generated by hbm2java
 */
public class UpromHost implements java.io.Serializable {

	private BigDecimal upromHostId;
	private Date createDt;
	private BigDecimal createUserId;
	private String hostCd;
	private String hostDs;
	private String hostNm;
	private Date updateDt;
	private BigDecimal updateUserId;
	private String activeFl;
	private String masterFl;

	public UpromHost() {
	}

	public UpromHost(BigDecimal upromHostId, Date createDt,
			BigDecimal createUserId, String hostDs, String hostNm,
			Date updateDt, BigDecimal updateUserId, String activeFl,
			String masterFl) {
		this.upromHostId = upromHostId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.hostDs = hostDs;
		this.hostNm = hostNm;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.activeFl = activeFl;
		this.masterFl = masterFl;
	}

	public UpromHost(BigDecimal upromHostId, Date createDt,
			BigDecimal createUserId, String hostCd, String hostDs,
			String hostNm, Date updateDt, BigDecimal updateUserId,
			String activeFl, String masterFl) {
		this.upromHostId = upromHostId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.hostCd = hostCd;
		this.hostDs = hostDs;
		this.hostNm = hostNm;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.activeFl = activeFl;
		this.masterFl = masterFl;
	}

	public BigDecimal getUpromHostId() {
		return this.upromHostId;
	}

	public void setUpromHostId(BigDecimal upromHostId) {
		this.upromHostId = upromHostId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getHostCd() {
		return this.hostCd;
	}

	public void setHostCd(String hostCd) {
		this.hostCd = hostCd;
	}

	public String getHostDs() {
		return this.hostDs;
	}

	public void setHostDs(String hostDs) {
		this.hostDs = hostDs;
	}

	public String getHostNm() {
		return this.hostNm;
	}

	public void setHostNm(String hostNm) {
		this.hostNm = hostNm;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public String getActiveFl() {
		return this.activeFl;
	}

	public void setActiveFl(String activeFl) {
		this.activeFl = activeFl;
	}

	public String getMasterFl() {
		return this.masterFl;
	}

	public void setMasterFl(String masterFl) {
		this.masterFl = masterFl;
	}

}
