package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserRoleOperation generated by hbm2java
 */
public class UserRoleOperation implements java.io.Serializable {

	private BigDecimal userRoleOperationId;
	private UserRole userRole;
	private Operation operation;
	private Date createDt;
	private BigDecimal createUserId;
	private Date updateDt;
	private BigDecimal updateUserId;

	public UserRoleOperation() {
	}

	public UserRoleOperation(BigDecimal userRoleOperationId, UserRole userRole,
			Operation operation, Date createDt, BigDecimal createUserId,
			Date updateDt, BigDecimal updateUserId) {
		this.userRoleOperationId = userRoleOperationId;
		this.userRole = userRole;
		this.operation = operation;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public BigDecimal getUserRoleOperationId() {
		return this.userRoleOperationId;
	}

	public void setUserRoleOperationId(BigDecimal userRoleOperationId) {
		this.userRoleOperationId = userRoleOperationId;
	}

	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

}
