package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private BigDecimal userRoleId;
	private Date createDt;
	private BigDecimal createUserId;
	private String internalRoleFl;
	private Date updateDt;
	private BigDecimal updateUserId;
	private String userRoleCd;
	private String userRoleNm;
	private Set userRoleOperations = new HashSet(0);
	private Set userses = new HashSet(0);

	public UserRole() {
	}

	public UserRole(BigDecimal userRoleId, Date createDt,
			BigDecimal createUserId, String internalRoleFl, Date updateDt,
			BigDecimal updateUserId, String userRoleNm) {
		this.userRoleId = userRoleId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.internalRoleFl = internalRoleFl;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.userRoleNm = userRoleNm;
	}

	public UserRole(BigDecimal userRoleId, Date createDt,
			BigDecimal createUserId, String internalRoleFl, Date updateDt,
			BigDecimal updateUserId, String userRoleCd, String userRoleNm,
			Set userRoleOperations, Set userses) {
		this.userRoleId = userRoleId;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.internalRoleFl = internalRoleFl;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
		this.userRoleCd = userRoleCd;
		this.userRoleNm = userRoleNm;
		this.userRoleOperations = userRoleOperations;
		this.userses = userses;
	}

	public BigDecimal getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(BigDecimal userRoleId) {
		this.userRoleId = userRoleId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getInternalRoleFl() {
		return this.internalRoleFl;
	}

	public void setInternalRoleFl(String internalRoleFl) {
		this.internalRoleFl = internalRoleFl;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

	public String getUserRoleCd() {
		return this.userRoleCd;
	}

	public void setUserRoleCd(String userRoleCd) {
		this.userRoleCd = userRoleCd;
	}

	public String getUserRoleNm() {
		return this.userRoleNm;
	}

	public void setUserRoleNm(String userRoleNm) {
		this.userRoleNm = userRoleNm;
	}

	public Set getUserRoleOperations() {
		return this.userRoleOperations;
	}

	public void setUserRoleOperations(Set userRoleOperations) {
		this.userRoleOperations = userRoleOperations;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
