package com.avnet.alapps.model.gsfc;

// Generated Apr 14, 2015 5:50:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserContact generated by hbm2java
 */
public class UserContact implements java.io.Serializable {

	private BigDecimal userContactId;
	private Contact contact;
	private ContactType contactType;
	private Users users;
	private Date createDt;
	private BigDecimal createUserId;
	private Date updateDt;
	private BigDecimal updateUserId;

	public UserContact() {
	}

	public UserContact(BigDecimal userContactId, Contact contact,
			ContactType contactType, Users users, Date createDt,
			BigDecimal createUserId, Date updateDt, BigDecimal updateUserId) {
		this.userContactId = userContactId;
		this.contact = contact;
		this.contactType = contactType;
		this.users = users;
		this.createDt = createDt;
		this.createUserId = createUserId;
		this.updateDt = updateDt;
		this.updateUserId = updateUserId;
	}

	public BigDecimal getUserContactId() {
		return this.userContactId;
	}

	public void setUserContactId(BigDecimal userContactId) {
		this.userContactId = userContactId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public ContactType getContactType() {
		return this.contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(BigDecimal updateUserId) {
		this.updateUserId = updateUserId;
	}

}
